### PR TITLE
fix(db): add additional connection pool for projection spooling

### LINKED ISSUE #7008: [Bug]: 2.42.0: unable to retrieve client by id
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.42.0

### Database

CockroachDB

### Database Version

23.1.12

### Describe the problem caused by this bug

Hello, I was too eager yesterday and upgraded my self-hosted ZITADEL instance to 2.42.0, but after that, it stopped working. I couldn't open the console, login to apps stopped working as well. Browser showed an error:
`{"error":"server_error","error_description":"unable to retrieve client by id"}`

and in the logs:
```
2023/11/30 22:08:14 ERROR request error oidc_error.parent="ID=QUERY-pCP8P Message=Errors.App.NotExisting Parent=(sql: no rows in result set)" oidc_error.description="unable to retrieve client by id" oidc_error.type=server_error
```

Luckily, downgrading to 2.41.6 fixed the problem. I'm running single node ZITADEL in Docker on Fedora 38, aarch64: 6.5.10-200.fc38.aarch64
Web browser tried: Firefox

### To reproduce

1. upgrade ZITADEL 2.41 to 2.42
2. ZITADEL stops working

### Screenshots

_No response_

### Expected behavior

_No response_

### Operating System

_No response_

### Relevant Configuration

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by muhlemmer**
We've observed deadlocks may occur in the projection handler when the SQL connection pool was exhausted.
This was because the queries and the handler share the same connection pool and some event reducers do additional queries that are not part of the current transaction.
When deadlocked, projections would become stale and outdated over time or might not even populate after a zitadel upgrade.

This changes adds an additional connection pool to zitadel for the projection spooler, so that it may continue operating independendly of the query workload.

Fixes #7008

### Definition of Ready

- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [x] PR is linked to the corresponding user story
- [x] Acceptance criteria are met
- [x] All open todos and follow ups are defined in a new ticket and justified
- [x] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [x] No debug or dead code
- [x] My code has no repetitions
- [x] Critical parts are tested automatically
- [x] Where possible E2E tests are implemented
- [x] Documentation/examples are up-to-date
- [x] All non-functional requirements are met
- [x] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Comment by muhlemmer** [comment]
I can confirm that ZITADEL upgraded fine from version v2.40.11 to a local build of this branch, which includes fix edaa41903edd4a480c50a8e595b968fb9fe21613. After upgrade I could login fine and logs are also more friendly:

```
tim@vivo:~/Compose/zitadel-upgrade> docker compose logs -f zitadel
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="initialization started" caller="/home/tim/Repositories/zitadel/zitadel/cmd/initialise/init.go:72"
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify user" caller="/home/tim/Repositories/zitadel/zitadel/cmd/initialise/verify_user.go:39" username=zitadel
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify database" caller="/home/tim/Repositories/zitadel/zitadel/cmd/initialise/verify_database.go:39" database=zitadel
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify grant" caller="/home/tim/Repositories/zitadel/zitadel/cmd/initialise/verify_grant.go:34" database=zitadel user=zitadel
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify zitadel" caller="/home/tim/Repositories/zitadel/zitadel/cmd/initialise/verify_zitadel.go:77" database=zitadel
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify system" caller="/home/tim/Repositories/zitadel/zitadel/cmd/initialise/verify_zitadel.go:38"
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify encryption keys" caller="/home/tim/Repositories/zitadel/zitadel/cmd/initialise/verify_zitadel.go:43"
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify projections" caller="/home/tim/Repositories/zitadel/zitadel/cmd/initialise/verify_zitadel.go:48"
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify eventstore" caller="/home/tim/Repositories/zitadel/zitadel/cmd/initialise/verify_zitadel.go:53"
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify events tables" caller="/home/tim/Repositories/zitadel/zitadel/cmd/initialise/verify_zitadel.go:58"
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify system sequence" caller="/home/tim/Repositories/zitadel/zitadel/cmd/initialise/verify_zitadel.go:63"
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify unique constraints" caller="/home/tim/Repositories/zitadel/zitadel/cmd/initialise/verify_zitadel.go:68"
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="setup started" caller="/home/tim/Repositories/zitadel/zitadel/cmd/setup/setup.go:67"
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=14_events_push
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=01_tables
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=02_assets
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=03_default_instance
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=05_last_failed
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=06_resource_owner_columns
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=07_logstore
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=08_auth_token_indexes
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=12_auth_users_otp_columns
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=13_fix_quota_constraints
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=15_current_projection_state
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=16_unique_constraint_lower
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=17_add_offset_col_to_current_states
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=config_change
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=projection_tables
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="starting migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:67" name=projection_tables
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.org_metadata2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.org_metadata2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.actions3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.actions3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.flow_triggers3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.flow_triggers3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.projects4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.projects4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.password_complexity_policies2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.password_complexity_policies2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.password_age_policies2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.password_age_policies2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.lockout_policies2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.lockout_policies2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.privacy_policies3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.privacy_policies3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.domain_policies2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.domain_policies2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.label_policies3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.label_policies3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.project_grants4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.project_grants4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.project_roles4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.project_roles4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.org_domains2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.org_domains2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.login_policies5
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.login_policies5
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.idps3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.idps3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.idp_templates5
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.idp_templates5
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.apps6
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.apps6
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.idp_user_links3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.idp_user_links3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.idp_login_policy_links5
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.idp_login_policy_links5
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.mail_templates2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.mail_templates2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.message_texts2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.message_texts2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.custom_texts2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.custom_texts2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.users10
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.users10
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.login_names3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.login_names3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.org_members4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.org_members4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.instance_domains
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.instance_domains
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.instance_members4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.instance_members4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.project_members4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.project_members4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.project_grant_members4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.project_grant_members4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.authn_keys2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.authn_keys2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.personal_access_tokens3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.personal_access_tokens3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.user_grants3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.user_grants3
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.user_metadata5
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.user_metadata5
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.user_auth_methods4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.user_auth_methods4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.instances
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.instances
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.secret_generators2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.secret_generators2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.smtp_configs1
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.smtp_configs1
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.sms_configs2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.sms_configs2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.oidc_settings2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.oidc_settings2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.notification_providers
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.notification_providers
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.keys4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.keys4
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.security_policies
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.security_policies
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.notification_policies
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.notification_policies
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.device_authorizations
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.device_authorizations
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.sessions8
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.sessions8
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.auth_requests
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.auth_requests
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.milestones
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.milestones
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.quotas
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.quotas
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.limits
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.limits
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="executing check" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:202" execute=0 projection=projections.restrictions2
zitadel-1  | time="2023-12-19T14:54:22Z" level=debug msg="projection set up" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/init.go:209" execute=0 projection=projections.restrictions2
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="verify migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:44" name=18_add_lower_fields_to_login_names
zitadel-1  | time="2023-12-19T14:54:22Z" level=info msg="starting migration" caller="/home/tim/Repositories/zitadel/zitadel/internal/migration/migration.go:67" name=18_add_lower_fields_to_login_names
zitadel-1  |   _____  ___   _____      _      ____    _____   _
zitadel-1  |  |__  / |_ _| |_   _|    / \    |  _ \  | ____| | |
zitadel-1  |    / /   | |    | |     / _ \   | | | | |  _|   | |
zitadel-1  |   / /_   | |    | |    / ___ \  | |_| | | |___  | |___
zitadel-1  |  /____| |___|   |_|   /_/   \_\ |____/  |_____| |_____|
zitadel-1  | 
zitadel-1  |  ===============================================================
zitadel-1  | 
zitadel-1  |  Version          : development-2023-12-19T16:46:45+02:00
zitadel-1  |  TLS enabled      : false
zitadel-1  |  External Secure  : false
zitadel-1  |  Console URL      : http://localhost:9001/ui/console
zitadel-1  |  Health Check URL : http://localhost:9001/debug/healthz
zitadel-1  | 
zitadel-1  |  Warning: you're using plain http without TLS. Be aware this is 
zitadel-1  |  not a secure setup and should only be used for test systems.         
zitadel-1  |  Visit: https://zitadel.com/docs/self-hosting/manage/tls_modes    
zitadel-1  | 
zitadel-1  |  ===============================================================
zitadel-1  | 
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.restrictions2
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.project_members4
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.project_grant_members4
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.org_members4
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.flow_triggers3
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.login_names3
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.project_roles4
zitadel-1  | 2023/12/19 14:54:23 INFO registered route endpoint=/oauth/v2/authorize
zitadel-1  | 2023/12/19 14:54:23 INFO registered route endpoint=/oauth/v2/device_authorization
zitadel-1  | 2023/12/19 14:54:23 INFO registered route endpoint=/oauth/v2/token
zitadel-1  | 2023/12/19 14:54:23 INFO registered route endpoint=/oauth/v2/introspect
zitadel-1  | 2023/12/19 14:54:23 INFO registered route endpoint=/oidc/v1/userinfo
zitadel-1  | 2023/12/19 14:54:23 INFO registered route endpoint=/oauth/v2/revoke
zitadel-1  | 2023/12/19 14:54:23 INFO registered route endpoint=/oidc/v1/end_session
zitadel-1  | 2023/12/19 14:54:23 INFO registered route endpoint=/oauth/v2/keys
zitadel-1  | time="2023-12-19T14:54:23Z" level=info msg="server is listening on [::]:8080" caller="/home/tim/Repositories/zitadel/zitadel/cmd/start/start.go:494"
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=1 projection=projections.login_names3
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.user_metadata5
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=2 projection=projections.login_names3
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.projects4
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=3 projection=projections.login_names3
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.sessions8
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.instance_members4
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=4 projection=projections.login_names3
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=5 projection=projections.login_names3
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.project_grants4
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.users10
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.apps6
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=1 projection=projections.apps6
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=1 projection=projections.users10
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=2 projection=projections.users10
zitadel-1  | time="2023-12-19T14:54:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=3 projection=projections.users10
zitadel-1  | time="2023-12-19T14:54:24Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=4 projection=projections.users10
zitadel-1  | time="2023-12-19T14:54:24Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=5 projection=projections.users10
zitadel-1  | time="2023-12-19T14:54:24Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=6 projection=projections.users10
zitadel-1  | time="2023-12-19T14:54:24Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=7 projection=projections.users10
zitadel-1  | time="2023-12-19T14:54:24Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.user_auth_methods4
zitadel-1  | time="2023-12-19T14:54:24Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=8 projection=projections.users10
zitadel-1  | time="2023-12-19T14:54:24Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=9 projection=projections.users10
zitadel-1  | time="2023-12-19T14:54:24Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=10 projection=projections.users10
zitadel-1  | time="2023-12-19T14:54:25Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.privacy_policies3
zitadel-1  | time="2023-12-19T14:54:28Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.lockout_policies2
zitadel-1  | time="2023-12-19T14:54:29Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.smtp_configs1
zitadel-1  | time="2023-12-19T14:54:30Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.login_policies5
zitadel-1  | time="2023-12-19T14:54:31Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.password_complexity_policies2
zitadel-1  | time="2023-12-19T14:54:31Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.auth_requests
zitadel-1  | time="2023-12-19T14:54:32Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.milestones
zitadel-1  | time="2023-12-19T14:54:35Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.oidc_settings2
zitadel-1  | time="2023-12-19T14:54:36Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.idp_user_links3
zitadel-1  | time="2023-12-19T14:54:37Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.password_age_policies2
zitadel-1  | time="2023-12-19T14:54:38Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.instances
zitadel-1  | time="2023-12-19T14:54:38Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.device_authorizations
zitadel-1  | time="2023-12-19T14:54:39Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.instance_domains
zitadel-1  | time="2023-12-19T14:54:39Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.limits
zitadel-1  | time="2023-12-19T14:54:40Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=auth.users2
zitadel-1  | time="2023-12-19T14:54:42Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.user_grants3
zitadel-1  | time="2023-12-19T14:54:42Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.notifications
zitadel-1  | time="2023-12-19T14:54:43Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.authn_keys2
zitadel-1  | time="2023-12-19T14:54:47Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.personal_access_tokens3
zitadel-1  | time="2023-12-19T14:54:49Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:54:50Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.notification_providers
zitadel-1  | time="2023-12-19T14:54:50Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=auth.refresh_tokens
zitadel-1  | time="2023-12-19T14:54:51Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.sms_configs2
zitadel-1  | time="2023-12-19T14:54:52Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.label_policies3
zitadel-1  | time="2023-12-19T14:54:52Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.quotas
zitadel-1  | time="2023-12-19T14:54:53Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.org_domains2
zitadel-1  | time="2023-12-19T14:54:54Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.custom_texts2
zitadel-1  | time="2023-12-19T14:54:54Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.mail_templates2
zitadel-1  | time="2023-12-19T14:54:58Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.message_texts2
zitadel-1  | time="2023-12-19T14:54:58Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.idp_templates5
zitadel-1  | time="2023-12-19T14:55:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.secret_generators2
zitadel-1  | time="2023-12-19T14:55:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.idps3
zitadel-1  | time="2023-12-19T14:55:05Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.idp_login_policy_links5
zitadel-1  | time="2023-12-19T14:55:06Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.notification_policies
zitadel-1  | time="2023-12-19T14:55:11Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.keys4
zitadel-1  | time="2023-12-19T14:55:11Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.domain_policies2
zitadel-1  | time="2023-12-19T14:55:15Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.org_metadata2
zitadel-1  | time="2023-12-19T14:55:18Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.security_policies
zitadel-1  | time="2023-12-19T14:55:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.actions3
zitadel-1  | time="2023-12-19T14:55:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.restrictions2
zitadel-1  | time="2023-12-19T14:55:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.project_members4
zitadel-1  | time="2023-12-19T14:55:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.project_grant_members4
zitadel-1  | time="2023-12-19T14:55:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.org_members4
zitadel-1  | time="2023-12-19T14:55:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.flow_triggers3
zitadel-1  | time="2023-12-19T14:55:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.project_roles4
zitadel-1  | time="2023-12-19T14:55:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.user_metadata5
zitadel-1  | time="2023-12-19T14:55:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.projects4
zitadel-1  | time="2023-12-19T14:55:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.sessions8
zitadel-1  | time="2023-12-19T14:55:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.instance_members4
zitadel-1  | time="2023-12-19T14:55:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.login_names3
zitadel-1  | time="2023-12-19T14:55:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.project_grants4
zitadel-1  | time="2023-12-19T14:55:23Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.apps6
zitadel-1  | time="2023-12-19T14:55:24Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.user_auth_methods4
zitadel-1  | time="2023-12-19T14:55:24Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.users10
zitadel-1  | time="2023-12-19T14:55:25Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.privacy_policies3
zitadel-1  | time="2023-12-19T14:55:28Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.lockout_policies2
zitadel-1  | time="2023-12-19T14:55:29Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.smtp_configs1
zitadel-1  | time="2023-12-19T14:55:30Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.login_policies5
zitadel-1  | time="2023-12-19T14:55:31Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.password_complexity_policies2
zitadel-1  | time="2023-12-19T14:55:31Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.auth_requests
zitadel-1  | time="2023-12-19T14:55:32Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.milestones
zitadel-1  | time="2023-12-19T14:55:35Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.oidc_settings2
zitadel-1  | time="2023-12-19T14:55:36Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.idp_user_links3
zitadel-1  | time="2023-12-19T14:55:37Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.password_age_policies2
zitadel-1  | time="2023-12-19T14:55:38Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.instances
zitadel-1  | time="2023-12-19T14:55:38Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.device_authorizations
zitadel-1  | time="2023-12-19T14:55:39Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.instance_domains
zitadel-1  | time="2023-12-19T14:55:39Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.limits
zitadel-1  | time="2023-12-19T14:55:42Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.user_grants3
zitadel-1  | time="2023-12-19T14:55:42Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.notifications
zitadel-1  | time="2023-12-19T14:55:43Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.authn_keys2
zitadel-1  | time="2023-12-19T14:55:47Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.personal_access_tokens3
zitadel-1  | time="2023-12-19T14:55:49Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:55:50Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.notification_providers
zitadel-1  | time="2023-12-19T14:55:50Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:55:50Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.auth.v1.AuthService/ListMyUserSessions org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:55:51Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.sms_configs2
zitadel-1  | time="2023-12-19T14:55:51Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=auth.tokens
zitadel-1  | time="2023-12-19T14:55:51Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=auth.user_sessions
zitadel-1  | time="2023-12-19T14:55:52Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.label_policies3
zitadel-1  | time="2023-12-19T14:55:52Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.quotas
zitadel-1  | time="2023-12-19T14:55:53Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.org_domains2
zitadel-1  | time="2023-12-19T14:55:54Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.custom_texts2
zitadel-1  | time="2023-12-19T14:55:54Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.mail_templates2
zitadel-1  | time="2023-12-19T14:55:58Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.message_texts2
zitadel-1  | time="2023-12-19T14:55:58Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.idp_templates5
zitadel-1  | time="2023-12-19T14:55:59Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=auth.user_sessions
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.secret_generators2
zitadel-1  | time="2023-12-19T14:56:00Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus= httpStatus= instance=245667973312806914 isSystemUser=false method= org=245667973312872450 path=/oauth/v2/token requestMethod=POST trigger=accessToken user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.milestones
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=auth.tokens
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.users10
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.login_names3
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:00Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.auth.v1.AuthService/ListMyProjectOrgs org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.privacy_policies3
zitadel-1  | time="2023-12-19T14:56:00Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.auth.v1.AuthService/GetMyPrivacyPolicy org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.users10
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.login_names3
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:00Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.admin.v1.AdminService/GetSupportedLanguages org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:00Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.auth.v1.AuthService/GetMyUser org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.users10
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.login_names3
zitadel-1  | time="2023-12-19T14:56:00Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.admin.v1.AdminService/GetAllowedLanguages org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:00Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.auth.v1.AuthService/GetMyUser org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.login_policies5
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:00Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.auth.v1.AuthService/GetMyLoginPolicy org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:00Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.auth.v1.AuthService/GetMyLabelPolicy org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.idps3
zitadel-1  | time="2023-12-19T14:56:00Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:00Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.auth.v1.AuthService/ListMyZitadelPermissions org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:00Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.auth.v1.AuthService/ListMyZitadelPermissions org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:01Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.auth.v1.AuthService/ListMyUserChanges org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:01Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:01Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:01Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:01Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.management.v1.ManagementService/ListGrantedProjects org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:01Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:01Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.user_metadata5
zitadel-1  | time="2023-12-19T14:56:01Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.management.v1.ManagementService/ListProjects org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:01Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.orgs1
zitadel-1  | time="2023-12-19T14:56:01Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.management.v1.ManagementService/ListUserMetadata org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:01Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.management.v1.ManagementService/ListGrantedProjects org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:01Z" level=info msg=activity caller="/home/tim/Repositories/zitadel/zitadel/internal/activity/activity.go:100" domain="http://localhost:9001" grpcStatus=0 httpStatus=200 instance=245667973312806914 isSystemUser=false method=/zitadel.management.v1.ManagementService/ListProjects org=245668278154821634 path= requestMethod= trigger=resourceAPI user=245667973312937986
zitadel-1  | time="2023-12-19T14:56:05Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.idp_login_policy_links5
zitadel-1  | time="2023-12-19T14:56:06Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.notification_policies
zitadel-1  | time="2023-12-19T14:56:11Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.keys4
zitadel-1  | time="2023-12-19T14:56:11Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.domain_policies2
zitadel-1  | time="2023-12-19T14:56:15Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.org_metadata2
zitadel-1  | time="2023-12-19T14:56:18Z" level=debug msg="trigger iteration" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" iteration=0 projection=projections.security_policies
```

File: cmd/start/start.go [hunk 1]
```diff
@@ -144,15 +149,16 @@ func startZitadel(config *Config, masterKey string, server chan<- *Server) error
 	}
 
 	config.Eventstore.Pusher = new_es.NewEventstore(esPusherDBClient)
-	config.Eventstore.Querier = old_es.NewCRDB(zitadelDBClient)
+	config.Eventstore.Querier = old_es.NewCRDB(queryDBClient)
```
Comment (livio-a) [inline cmd/start/start.go:152]: isn't there a problem since the eventstore querier will also be used inside the projections to retrieve additional events, which is one of the reasons for a potential deadlock, right?

**Review by livio-a — APPROVED** [review]
