### PR TITLE
fix: add resourceowner to check for project in project grant

### LINKED ISSUE #8685: [Bug]: Can not remove project grant
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.60.x

### Database

PostgreSQL

### Describe the problem caused by this bug

I can grant a project successfully owned by org **Company**, with header `x-zitadel-orgid` org **Customer** and using token Role IAM.
https://zitadel.com/docs/apis/resources/mgmt/management-service-add-project-grant

When I remove that grant ID with the header `x-zitadel-orgid` org **Customer**. it returns the error: `Project not found`
And If I remove that grant ID with the header `x-zitadel-orgid` org **Company**. it returns the error: `Grant not found`
https://zitadel.com/docs/apis/resources/mgmt/management-service-remove-project-grant

**Expected**: header `x-zitadel-orgid` org **Company** should be successfully

### PR DESCRIPTION
**Pull request by stebenz**
# Which Problems Are Solved

Resource owner can be different than expected if the provided x-zitadel-orgid header is provided.

# How the Problems Are Solved

Check that the project is only checked with the correct resource owner to avoid unexpected situations.

# Additional Changes

None

# Additional Context

Closes #8685

### CODE REVIEW

File: internal/command/project_grant_model.go [hunk 1]
```diff
@@ -114,30 +114,44 @@ func (wm *ProjectGrantWriteModel) Query() *eventstore.SearchQueryBuilder {
 type ProjectGrantPreConditionReadModel struct {
 	eventstore.WriteModel
 
+	ResourceOwner    string
```
Comment (livio-a) [inline internal/command/project_grant_model.go:117]: the `ResourceOwner` already exists on the `WriteModel`

**Review by livio-a — CHANGES_REQUESTED** [review]
can we somehow write a test which checks that the the current behavior is not possible anymore?

File: internal/command/project_grant_model.go (hunk 1 above)
Comment (stebenz) [reply internal/command/project_grant_model.go]: removed ResourceOwner and added tests to unit tests for unexpected scenario

**Review by livio-a — APPROVED** [review]
