### PR TITLE
fix(console): jwt provider callback urls #11589

### LINKED ISSUE #11589: [Bug]: JWT IdP proxy call to /idps/jwt returns Errors.AuthRequest.MissingParameters although original query params are forwarded intact (v4.9.1)
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v4.9.1

### Database

PostgreSQL

### Database Version

_No response_

### Describe the problem caused by this bug

**Related to:** (4d66a786c88ba624bb8ca7bd67a128b920e0cb7f)

**What happened?**
While integrating JWT Identity Provider exactly as described in the documentation (https://zitadel.com/docs/guides/integrate/identity-providers/jwt_idp), the proxy step fails.

ZITADEL redirects the browser to my configured jwtEndpoint with **authRequestID** & **userAgentID** query parameters. My jwtEndpoint then proxies the request back to ZITADEL’s **/idps/jwt** endpoint, attaching the generated JWT and forwarding the original query parameters unchanged.

ZITADEL responds with **HTTP 400 Bad Request** and body:

**ID=LOGIN-adfzz Message=Errors.AuthRequest.MissingParameters**

**Evidence (request/response)**
The proxied request sent to ZITADEL:

Method: GET
URL:
http://zitadel.localhost:8081/idps/jwt?authRequestID=359867306563600387&userAgentID=JZeqi-9z9sIFfpRvx79Ltf30ZzGdhUgsPT0UTu5YB-ZNNg
Header:
x-zitadel-jwt: <JWT...>

Response from ZITADEL:
Status: 400
Body: ID=LOGIN-adfzz Message=Errors.AuthRequest.MissingParameters

**Why I think it’s related to this commit**
The error seems to originate from changes in commit (4d66a786c88ba624bb8ca7bd67a128b920e0cb7f) at:
R370

In my tests, if I intentionally modify the userAgentID query parameter, the request fails during decryption (around DecryptString / line ~365). In the real flow I’m not modifying the query parameters, but I still receive Errors.AuthRequest.MissingParameters.

**Expected behavior**
Following the official documentation, proxying the request to /idps/jwt with the JWT in the configured header and forwarding all original query parameters unchanged should succeed. 

**Environment**
ZITADEL version: v4.9.1
Deployment: self-hosted Docker (local)
URL: http://zitadel.localhost:8081
TLS mode: disabled (local)
JWT header name: x-zitadel-jwt

### To reproduce

1. Start a self-hosted ZITADEL instance (tested with v4.9.1) reachable at e.g. http://zitadel.localhost:8081.
2. Implement the JWT Endpoint as described in the docs 
3. Configure a JWT Identity Provider in ZITADEL
4. Trigger the login via the JWT IdP

Observe that the proxied request to /idps/jwt returns:

HTTP 400

Body: Message=Errors.AuthRequest.MissingParameters

### Screenshots

Request {
  method: 'GET',
  url: 'http://zitadel.localhost:8081/idps/jwt?authRequestID=359867306563600387&userAgentID=JZeqi-9z9sIFfpRvx79Ltf30ZzGdhUgsPT0UTu5YB-ZNNg',
  headers: Headers(2) {
    'accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'x-zitadel-jwt' => 'eyJraW...',
    [immutable]: false
  },
  redirect: 'manual',
  fetcher: null,
  signal: AbortSignal { aborted: false, reason: undefined, onabort: null },
  cf: undefined,
  integrity: '',
  keepalive: false,
  cache: undefined,
  body: null,
  bodyUsed: false
}
Response {
  status: 400,
  statusText: 'Bad Request',
  headers: Headers(5) {
    'content-length' => '60',
    'content-type' => 'text/plain; charset=utf-8',
    'date' => 'Fri, 13 Feb 2026 14:40:29 GMT',
    'x-content-type-options' => 'nosniff',
    'x-robots-tag' => 'none',
    [immutable]: true
  },
  ok: false,
  redirected: false,
  url: 'http://zitadel.localhost:8081/idps/jwt?authRequestID=359867306563600387&userAgentID=JZeqi-9z9sIFfpRvx79Ltf30ZzGdhUgsPT0UTu5YB-ZNNg',
  webSocket: null,
  cf: undefined,
  type: 'default',
  body: ReadableStream {
    locked: false,
    [state]: 'readable',
    [supportsBYOB]: true,
    [length]: 60n
  },
  bodyUsed: false
}
zitadel body ID=LOGIN-adfzz Message=Errors.AuthRequest.MissingParameters

[wrangler:info] GET /aaa 400 Bad Request (15ms)

### Expected behavior

_No response_

### Operating System

_No response_

### Relevant Configuration

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by conblem**
# Which Problems Are Solved
The console didn't specify any callback url's for the JWT idp provider.

# How the Problems Are Solved

Added callback url's to the JWT idp provider screen in the management console.

# Additional Changes

# Additional Context

- Closes #11589

### CODE REVIEW

File: console/src/app/modules/providers/provider-jwt/provider-jwt.component.ts [hunk 1]
```diff
@@ -68,6 +68,7 @@ export class ProviderJWTComponent {
     this.service$,
   );
   public expandWhatNow$ = this.nextSvc.expandWhatNow(this.id$, this.activateLink$, this.justCreated$);
+  protected readonly copyUrls$ = this.nextSvc.jwtCallbackUrls();
```
[the remark this answers is not in the document]
Comment (conblem) [reply console/src/app/modules/providers/provider-jwt/provider-jwt.component.ts:71]: https://angular.dev/style-guide#use-protected-on-class-members-that-are-only-used-by-a-components-template not true

File: console/src/app/modules/providers/provider-next/provider-next.service.ts [hunk 2]
```diff
@@ -95,6 +95,21 @@ export class ProviderNextService {
     );
   }
 
+  jwtCallbackUrls(): Observable<CopyUrl[]> {
+    return this.env.env.pipe(
+      map((env) => [
+        {
+          label: 'Login V1 Callback URL',
+          url: `${env.issuer}/ui/login/login/jwt/authorize`,
```
Comment (wim07101993) [inline console/src/app/modules/providers/provider-next/provider-next.service.ts]: is this url correct? In the docs it says https://accounts.test.com/ui/login/idps/jwt

Comment (wim07101993) [reply console/src/app/modules/providers/provider-next/provider-next.service.ts]: (https://zitadel.com/docs/guides/integrate/identity-providers/jwt_idp)

Comment (conblem) [reply console/src/app/modules/providers/provider-next/provider-next.service.ts]: Honestly I just took those from the comment you made here https://github.com/zitadel/zitadel/issues/11589#issuecomment-4116595110

But I think at least one of the these two must be false (found on the doc page you linked)
CleanShot 2026-04-02 at 10 16 01
CleanShot 2026-04-02 at 10 16 25

Comment (wim07101993) [reply console/src/app/modules/providers/provider-next/provider-next.service.ts]: Oh, sorry for that. The authorize url is incorrect. It needs to be the jwt url.

Comment (wim07101993) [reply console/src/app/modules/providers/provider-next/provider-next.service.ts]: That is not supposed to be there. Both should be the idp links as in the example:
- `https://accounts.test.com/idps/jwt`
- `https://accounts.test.com/ui/login/idps/jwt`

Comment (wim07101993) [reply console/src/app/modules/providers/provider-next/provider-next.service.ts]: I created a fix in https://github.com/zitadel/zitadel/pull/11989
