### PR TITLE
fix(setup): init projections

### LINKED ISSUE #6969: [Bug]: ZITADEL latest version stuck on DB migration using Postgres
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.41.4

### Describe the problem caused by this bug

ZITADEL using postgres 14 is stuck in the migration to recreate its database in the projection schema, causing that it never finishes initialization and not being usable. it is able to create the projections schema, but no tables are inside.

### To reproduce

1. use the following docker compose configuration:
```
  pgdb:
    image: postgres:14
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '0.0.0.0:5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.data/pgdb:/var/lib/postgresql/data
      - ./.data/sqlscripts:/companyabc/sqlscripts
  zitadel:
    restart: 'always'
    image: 'ghcr.io/zitadel/zitadel:v2.41.4'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_POSTGRES_HOST=pgdb'
      - 'ZITADEL_DATABASE_POSTGRES_DATABASE=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_PORT=5432'
      - 'ZITADEL_DATABASE_POSTGRES_USER_USERNAME=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable'
      - 'ZITADEL_EXTERNALSECURE=false'
      - 'ZITADEL_EXTERNALPORT=8085'
    depends_on:
      pgdb:
        condition: service_started
    ports:
      - '8085:8080'
```
2. run docker dompose up -d
3. monitor the zitadel container and it will get stuck while running the migration, infinitely on step=15_current_projection_state, like this: 

### Screenshots

image
image

### Expected behavior

To get the migration to finish 
To see all the tables in the zitadel schema in my postgres database (projections)
To be able to access zitadel local instance through the browser

### Operating System

Device: Macbook Pro M1
OS: Sonoma 14.1.1
Browser: Chrome (not relevant for this issue)

### Relevant Configuration

```
  pgdb:
    image: postgres:14
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '0.0.0.0:5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.data/pgdb:/var/lib/postgresql/data
      - ./.data/sqlscripts:/companyabc/sqlscripts
  zitadel:
    restart: 'always'
    image: 'ghcr.io/zitadel/zitadel:v2.41.4'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_POSTGRES_HOST=pgdb'
      - 'ZITADEL_DATABASE_POSTGRES_DATABASE=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_PORT=5432'
      - 'ZITADEL_DATABASE_POSTGRES_USER_USERNAME=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable'
      - 'ZITADEL_EXTERNALSECURE=false'
      - 'ZITADEL_EXTERNALPORT=8085'
    depends_on:
      pgdb:
        condition: service_started
    ports:
      - '8085:8080'
```

### Additional Context

Logs I'm getting:

```
2023-11-23 11:56:12 time="2023-11-23T17:56:12Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:71"
2023-11-23 11:56:12 time="2023-11-23T17:56:12Z" level=fatal msg="unable to initialize the database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:64" error="ID=DATAB-0pIWD Message=Errors.Database.Connection.Failed Parent=(failed to connect to `host=pgdb user=postgres database=postgres`: dial error (dial tcp 172.27.0.6:5432: connect: connection refused))"
2023-11-23 11:56:15 time="2023-11-23T17:56:14Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:71"
2023-11-23 11:56:15 time="2023-11-23T17:56:14Z" level=fatal msg="unable to initialize the database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:64" error="ID=DATAB-0pIWD Message=Errors.Database.Connection.Failed Parent=(failed to connect to `host=pgdb user=postgres database=postgres`: dial error (dial tcp 172.27.0.6:5432: connect: connection refused))"
2023-11-23 11:56:16 time="2023-11-23T17:56:16Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:71"
2023-11-23 11:56:17 time="2023-11-23T17:56:17Z" level=info msg="verify user" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_user.go:39" username=postgres
2023-11-23 11:56:17 time="2023-11-23T17:56:17Z" level=info msg="verify database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_database.go:39" database=postgres
2023-11-23 11:56:17 time="2023-11-23T17:56:17Z" level=info msg="verify grant" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_grant.go:34" database=postgres user=postgres
2023-11-23 11:56:17 time="2023-11-23T17:56:17Z" level=info msg="verify zitadel" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:76" database=postgres
2023-11-23 11:56:17 time="2023-11-23T17:56:17Z" level=info msg="verify system" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:37"
2023-11-23 11:56:17 time="2023-11-23T17:56:17Z" level=info msg="verify encryption keys" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:42"
2023-11-23 11:56:17 time="2023-11-23T17:56:17Z" level=info msg="verify projections" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:47"
2023-11-23 11:56:17 time="2023-11-23T17:56:17Z" level=info msg="verify eventstore" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:52"
2023-11-23 11:56:17 time="2023-11-23T17:56:17Z" level=info msg="verify events tables" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:57"
2023-11-23 11:56:18 time="2023-11-23T17:56:18Z" level=info msg="verify system sequence" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:62"
2023-11-23 11:56:18 time="2023-11-23T17:56:18Z" level=info msg="verify unique constraints" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:67"
2023-11-23 11:56:18 time="2023-11-23T17:56:18Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:65"
2023-11-23 11:56:19 time="2023-11-23T17:56:19Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:44" name=14_events_push
2023-11-23 11:56:19 time="2023-11-23T17:56:19Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:44" name=01_tables
2023-11-23 11:56:19 time="2023-11-23T17:56:19Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:44" name=02_assets
2023-11-23 11:56:20 time="2023-11-23T17:56:20Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:44" name=03_default_instance
2023-11-23 11:56:20 time="2023-11-23T17:56:20Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:44" name=05_last_failed
2023-11-23 11:56:20 time="2023-11-23T17:56:20Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:44" name=06_resource_owner_columns
2023-11-23 11:56:20 time="2023-11-23T17:56:20Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:44" name=07_logstore
2023-11-23 11:56:20 time="2023-11-23T17:56:20Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:44" name=08_auth_token_indexes
2023-11-23 11:56:21 time="2023-11-23T17:56:21Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:44" name=12_auth_users_otp_columns
2023-11-23 11:56:21 time="2023-11-23T17:56:21Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:44" name=13_fix_quota_constraints
2023-11-23 11:56:21 time="2023-11-23T17:56:21Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:44" name=15_current_projection_state
2023-11-23 11:56:21 time="2023-11-23T17:56:21Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:136" migration step=15_current_projection_state
2023-11-23 11:56:27 time="2023-11-23T17:56:27Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:136" migration step=15_current_projection_state
2023-11-23 11:56:32 time="2023-11-23T17:56:32Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:136" migration step=15_current_projection_state
2023-11-23 11:56:37 time="2023-11-23T17:56:37Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:136" migration step=15_current_projection_state
2023-11-23 11:56:42 time="2023-11-23T17:56:42Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:136" migration step=15_current_projection_state
2023-11-23 11:56:48 time="2023-11-23T17:56:47Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:136" migration step=15_current_projection_state
2023-11-23 11:56:53 time="2023-11-23T17:56:53Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:136" migration step=15_current_projection_state
2023-11-23 11:56:58 time="2023-11-23T17:56:58Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:136" migration step=15_current_projection_state
2023-11-23 11:57:03 time="2023-11-23T17:57:03Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:136" migration step=15_current_projection_state
2023-11-23 11:57:08 time="2023-11-23T17:57:08Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:136" migration step=15_current_projection_state
2023-11-23 11:57:13 time="2023-11-23T17:57:13Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:136" migration step=15_current_projection_state
```

### LINKED ISSUE #7267: [Bug]: Upgrade from 2.41 to higher version break the instance
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.41.14

### Database

CockroachDB

### Database Version

23.1.14

### Describe the problem caused by this bug

Zitadel instances in unable to function.

Logs:

time="2024-01-20T01:38:18Z" level=info msg="scheduled trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:153" error="sql: transaction has already been committed or rolled back" instance=227082933419115299 projection=projections.apps6
 
22:38:18.893
time="2024-01-20T01:38:18Z" level=error msg="statement execution failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:472" error="sql: transaction has already been committed or rolled back" projection=projections.apps6
 
22:38:18.893
time="2024-01-20T01:38:18Z" level=warning msg="unable to get failure count" aggregate=229919536432808994 caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/failed_event.go:53" error="ID=CRDB-Unnex Message=unable to update failure count Parent=(sql: transaction has already been committed or rolled back)" instance=227082933419115299 projection=projections.apps6 sequence=159
 
22:38:18.893
time="2024-01-20T01:38:18Z" level=warning msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" error="sql: transaction has already been committed or rolled back" projection=projections.apps6
 
22:38:19.894
time="2024-01-20T01:38:19Z" level=info msg="scheduled trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:153" error="sql: transaction has already been committed or rolled back" instance=227082933419115299 projection=projections.apps6
 
22:38:20.397
time="2024-01-20T01:38:20Z" level=error msg="statement execution failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:472" error="ID=CRDB-YdOXD Message=create savepoint failed Parent=(sql: transaction has already been committed or rolled back)" projection=projections.apps6
 
22:38:20.397
time="2024-01-20T01:38:20Z" level=warning msg="unable to get failure count" aggregate=229919536432808994 caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/failed_event.go:53" error="ID=CRDB-Unnex Message=unable to update failure count Parent=(sql: transaction has already been committed or rolled back)" instance=227082933419115299 projection=projections.apps6 sequence=197
 
22:38:20.397
time="2024-01-20T01:38:20Z" level=warning msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" error="sql: transaction has already been committed or rolled back" projection=projections.apps6
 
22:38:21.398
time="2024-01-20T01:38:21Z" level=info msg="scheduled trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:153" error="sql: transaction has already been committed or rolled back" instance=227082933419115299 projection=projections.apps6
 
22:38:21.901
time="2024-01-20T01:38:21Z" level=error msg="statement execution failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:472" error="ID=CRDB-pKtsr Message=exec failed Parent=(sql: transaction has already been committed or rolled back)" projection=projections.apps6
 
22:38:21.901
time="2024-01-20T01:38:21Z" level=warning msg="unable to get failure count" aggregate=229919536432808994 caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/failed_event.go:53" error="ID=CRDB-Unnex Message=unable to update failure count Parent=(sql: transaction has already been committed or rolled back)" instance=227082933419115299 projection=projections.apps6 sequence=158
 
22:38:21.901
time="2024-01-20T01:38:21Z" level=warning msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" error="sql: transaction has already been committed or rolled back" projection=projections.apps6
 
22:38:22.462
2024-01-20 01:38:22.462 UTC [498] LOG stats: 0 xacts/s, 0 queries/s, 0 client parses/s, 0 server parses/s, 0 binds/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
 
22:38:22.902
time="2024-01-20T01:38:22Z" level=info msg="scheduled trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:153" error="sql: transaction has already been committed or rolled back" instance=227082933419115299 projection=projections.apps6
 
22:38:23.404
time="2024-01-20T01:38:23Z" level=warning msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" error="sql: transaction has already been committed or rolled back" projection=projections.apps6
 
22:38:24.405
time="2024-01-20T01:38:24Z" level=info msg="scheduled trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:153" error="sql: transaction has already been committed or rolled back" instance=227082933419115299 projection=projections.apps6
 
22:38:24.913
time="2024-01-20T01:38:24Z" level=error msg="statement execution failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:472" error="sql: transaction has already been committed or rolled back" projection=projections.apps6
 
22:38:24.913
time="2024-01-20T01:38:24Z" level=warning msg="unable to get failure count" aggregate=229919536432808994 caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/failed_event.go:53" error="ID=CRDB-Unnex Message=unable to update failure count Parent=(sql: transaction has already been committed or rolled back)" instance=227082933419115299 projection=projections.apps6 sequence=159
 
22:38:24.913
time="2024-01-20T01:38:24Z" level=warning msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" error="sql: transaction has already been committed or rolled back" projection=projections.apps6
 
22:38:25.914
time="2024-01-20T01:38:25Z" level=info msg="scheduled trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:153" error="sql: transaction has already been committed or rolled back" instance=227082933419115299 projection=projections.apps6

### To reproduce

1. Install version 2.41.14 in kubernetes.
2. Upgrade

### Screenshots

_No response_

### Expected behavior

Upgrade is sucessfull

### Operating System

Kubernetes v 1.28.2 OKE (Oracle Cloud)

### Relevant Configuration

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by adlerhurst**
As reported by multiple users startup of ZITADEL after leaded to downtime and worst case rollbacks to the previously deployed version.

The problem starts rising when there are too many events to process after the start of ZITADEL. The root cause are changes on projections (database tables) which must be recomputed. This PR solves this problem by adding a new step to the setup phase which prefills the projections. The step can be enabled by adding the `--init-projections`-flag to `setup`, `start-from-init` and `start-from-setup`. Setting this flag results in potentially longer duration of the setup phase but reduces the risk of the problems mentioned in the paragraph above.

closes [#7180](https://github.com/zitadel/zitadel/issues/7180)
closes #6969
closes #7267

Even though this is a feature it's released as fix so that we can back port to earlier revisions.

### CODE REVIEW

File: cmd/setup/setup.go [hunk 1]
```diff
@@ -58,6 +89,9 @@ Requirements:
 
 func Flags(cmd *cobra.Command) {
 	cmd.PersistentFlags().StringArrayVar(&stepFiles, "steps", nil, "paths to step files to overwrite default steps")
+	cmd.Flags().Bool("init-projections", viper.GetBool("init-projections"), "initializes projections after they are created")
+	err := viper.BindPFlag("InitProjections", cmd.Flags().Lookup("init-projections"))
```
Comment (livio-a) [inline cmd/setup/setup.go:93]: the binding doesn't work for setup and init at the same time

**Review by livio-a — CHANGES_REQUESTED** [review]

**Review by livio-a — APPROVED** [review]
