### PR TITLE
fix(login): enable explicit IDP linking using existing session id

### LINKED ISSUE #11191: [Bug]: Account linking fails with "validation_failed" error using login V2
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

v4.7.5

### Database

None

### Database Version

_No response_

### Describe the problem caused by this bug

I want to perform account linking between a username + password user and a SAML IDP external user with the same email, using login V2 on the Service Provider (my Zitadel instance)

When I have no user with the same email as the SAML IDP user on the SP, login works as expected, when I create a username + password user with the same email in the SP, and then try to log in with the IDP user, an error occurs, also, the error does not provide a title or detailed description of what failed.

Image

### To reproduce

1. Create a SAML IDP connection
2. Create a user in the SP with the same email and set an initial password and email verified
3. Try to log in using the external IDP with a user that has the same email

### Screenshots

Console error:

Image

### Expected behavior

Identities should be linked correctly.

### Operating System

_No response_

### Relevant Configuration

IDP settings:

Image

Image

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by peintnermax**
Closes #11191 

# Which Problems Are Solved

This PR fixes the IDP linking for accounts with no authentication method.
We strictly validate session ownership and generate a hash of the sessionId + the user's fingerprintId cookie. This hash is passed to the IDP as linkFingerprint.

This PR addtionally addresses TypeScript errors regarding unknown types in catch blocks within the IDP intent processing logic. It ensures that errors occurring during IDP linking are safely handled, and that meaningful error messages are propagated to the client-side redirect URLs.

# How the Problems Are Solved

- Safely handle unknown errors: Updated catch blocks in `processIDPCallback` to check if the caught object is an instance of Error before accessing error.message.
- Fix "IDP Taken" check: Implemented a safe check for the gRPC error code 6 (Already Exists) by casting the error, resolving the Property 'code' does not exist on type 'unknown' build error.
- Error Propagation: The specific error message is now passed to the linking-failed page params, allowing for better user feedback instead of generic errors.

### CODE REVIEW

File: apps/login/src/app/(login)/authenticator/set/page.tsx [hunk 1]
```diff
@@ -41,23 +41,19 @@ export default async function Page(props: { searchParams: Promise<Record<string
...
+  async function getAuthMethodsAndUser(session?: Session) {
     const userId = session?.factors?.user?.id;
 
     if (!userId) {
       throw Error("Could not get user id from session");
     }
 
-    return listAuthenticationMethodTypes({ serviceConfig, userId,
-    }).then((methods) => {
+    return listAuthenticationMethodTypes({ serviceConfig, userId }).then((methods) => {
```
Comment (conblem) [inline apps/login/src/app/(login)/authenticator/set/page.tsx]: I think it would make sense to use async await here instead of 3 nested returns

File: apps/login/src/app/(login)/authenticator/set/page.tsx [hunk 2]
```diff
@@ -69,21 +65,21 @@ export default async function Page(props: { searchParams: Promise<Record<string
...
     });
   }
 
   async function loadSessionById(sessionId: string, organization?: string) {
     const recent = await getSessionCookieById({ sessionId, organization });
-    return getSession({ serviceConfig, sessionId: recent.id,
-      sessionToken: recent.token,
-    }).then((sessionResponse) => {
-      return getAuthMethodsAndUser(serviceConfig.baseUrl, sessionResponse.session);
+    return getSession({ serviceConfig, sessionId: recent.id, sessionToken: recent.token }).then((sessionResponse) => {
```
Comment (conblem) [inline apps/login/src/app/(login)/authenticator/set/page.tsx]: here i would also like to see async await otherwise the async keyword isn't even used.

File: apps/login/src/app/(login)/authenticator/set/page.tsx [hunk 3]
```diff
@@ -122,7 +119,9 @@ export default async function Page(props: { searchParams: Promise<Record<string
     redirect(`/verify?` + params);
   }
 
-  const identityProviders = await getActiveIdentityProviders({ serviceConfig, orgId: sessionWithData.factors?.user?.organizationId,
+  const identityProviders = await getActiveIdentityProviders({
```
Comment (conblem) [inline apps/login/src/app/(login)/authenticator/set/page.tsx]: can be replaced by  ```const { identityProviders } = await getActiveIdentityProviders(....)```

File: apps/login/src/components/session-item.tsx [hunk 4]
```diff
@@ -141,7 +141,7 @@ export function SessionItem({ session, reload, requestId }: { session: Session;
 
             <XCircleIcon
               className="h-5 w-5 opacity-50 transition-all hover:opacity-100 group-hover:block sm:hidden"
-              onClick={(event) => {
+              onClick={(event: React.MouseEvent) => {
```
Comment (conblem) [inline apps/login/src/components/session-item.tsx]: why the explicit type? Does using async work?

```jsx
            <XCircleIcon
              className="h-5 w-5 opacity-50 transition-all hover:opacity-100 group-hover:block sm:hidden"
              onClick={async (event) => {
                event.preventDefault();
                event.stopPropagation();
                await clearSessionId(session.id);
                reload();
              }}
            />
```

File: apps/login/src/lib/server/idp-intent.ts [hunk 5]
```diff
@@ -111,17 +113,20 @@ export async function processIDPCallback({
...
   id: string;
   token: string;
   requestId?: string;
   organization?: string;
-  link?: string;
   postErrorRedirectUrl?: string;
+  sessionId?: string;
+  linkFingerprint?: string;
 }): Promise<{ redirect?: string; error?: string }> {
+  // ... (headers and config retrieval) ...
```
Comment (conblem) [inline apps/login/src/lib/server/idp-intent.ts]: this function is way to long imo and is already split into multiple cases so id rather have these as seperate functions instead of comments.

File: apps/login/src/lib/server/idp-intent.ts [hunk 6]
```diff
@@ -296,11 +307,63 @@ export async function processIDPCallback({
         return { error: t("errors.sessionCreationFailed") };
       } catch (error) {
         console.error("[IDP Process] Error linking IDP:", error);
-        const params = buildRedirectParams();
+        const errorMessage = error instanceof Error ? error.message : t("errors.unknownError");
+        let params = buildRedirectParams({ error: errorMessage });
+        if ((error as any)?.code === 6) {
```
Comment (conblem) [inline apps/login/src/lib/server/idp-intent.ts]: preffer using the in operator: ```if ('code' in error && error.code === 6) {}```

File: apps/login/src/app/(login)/authenticator/set/page.tsx (hunk 1 above)
Comment (peintnermax) [reply apps/login/src/app/(login)/authenticator/set/page.tsx]: sure. makes sense 👍

File: apps/login/src/app/(login)/authenticator/set/page.tsx (hunk 3 above)
Comment (peintnermax) [reply apps/login/src/app/(login)/authenticator/set/page.tsx]: done 👍

File: apps/login/src/components/session-item.tsx (hunk 4 above)
Comment (peintnermax) [reply apps/login/src/components/session-item.tsx]: async does work, the type is not strictly required. I've changed it

File: apps/login/src/lib/server/idp-intent.ts (hunk 6 above)
Comment (peintnermax) [reply apps/login/src/lib/server/idp-intent.ts]: done.

File: apps/login/src/lib/server/idp-intent.ts (hunk 5 above)
Comment (peintnermax) [reply apps/login/src/lib/server/idp-intent.ts]: I've refactored the file, creating multiptle handlers that are executed sequentially. they share the same context.

File: apps/login/src/app/(login)/authenticator/set/page.tsx (hunk 2 above)
Comment (peintnermax) [reply apps/login/src/app/(login)/authenticator/set/page.tsx]: done

File: apps/login/src/lib/server/idp-intent.ts (hunk 5 above)
Comment (conblem) [reply apps/login/src/lib/server/idp-intent.ts]: really liking the change thanks 👍

File: apps/login/src/lib/server/idp-intent.ts [hunk 7]
```diff
@@ -230,57 +260,152 @@ export async function processIDPCallback({
       }
 
       return { error: t("errors.sessionCreationFailed") };
+    } catch (error) {
+      console.error("[IDP Process] Error linking IDP:", error);
+      const errorMessage = error instanceof Error ? error.message : t("errors.unknownError");
+      let params = buildRedirectParams({ error: errorMessage });
+      if (error && typeof error === "object" && "code" in error && (error as { code: unknown }).code === 6) {
```
Comment (conblem) [inline apps/login/src/lib/server/idp-intent.ts]: I don't think the as casting is needed but maybe it would be easier to just use 

```js
import { ConnectError, Code } from "@zitadel/client";

if(error instanceof ConnectError && error.code === Code.AlreadyExists) {
  params = buildRedirectParams({ error: "external_idp_taken" });
}
```

Comment (peintnermax) [reply apps/login/src/lib/server/idp-intent.ts]: good hint. I'll implement that 👍
