### PR TITLE
fix: correctly delete sessions created before 2.42

### LINKED ISSUE #7011: [Bug]: can't terminate user session using service account
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.42.0

### Database

CockroachDB

### Database Version

_No response_

### Describe the problem caused by this bug

1. Can't terminate user sessions using service account with `Org User Manager` role (tried `Org Owner` as well). Error I'm getting is `membership not found (AUTHZ-cdgFk)`. Sessions were created prior to upgrade.
2. After granting `Iam User Manager` problem goes away, but sessions owned by the organization aren't actually deleted. They are still being returned by `/v2beta/sessions/search`
3. There is no migration path for adding `session.delete` permission to the Org/Iam roles. I had to go over PR to understand what was actually changed and add role permissions manually to our config file. If this a correct way to upgrade, it should probably go into release notes or upgrade instructions.

### To reproduce

The first part kinda tricky to reproduce, because reproduction scenario requires sessions that were created prior to 2.42.0. I assume this happens because of change in resource ownerships. Session have been owned by the organization, but since 2.42.0 it's owned by the instance, by the looks of it.

### Screenshots

_No response_

### Expected behavior

_No response_

### Operating System

_No response_

### Relevant Configuration

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by livio-a**
closes #7011 

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

File: internal/command/resource_ower_model.go [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+	instanceID    string
+	aggregateType eventstore.AggregateType
+	aggregateID   string
+
+	resourceOwner string
+}
+
+func NewResourceOwnerModel(ctx context.Context, aggregateType eventstore.AggregateType, aggregateID string) *resourceOwnerModel {
+	return &resourceOwnerModel{
+		instanceID:    authz.GetInstance(ctx).InstanceID(),
```
Comment (stebenz) [inline internal/command/resource_ower_model.go:22]: can we move the context read outside of the model? just remove the context from the parameters

File: internal/command/session.go [hunk 2]
```diff
@@ -400,7 +400,19 @@ func (c *Commands) checkSessionTerminationPermission(ctx context.Context, model
 	if model.UserID != "" && model.UserID == authz.GetCtxData(ctx).UserID {
 		return nil
 	}
-	return c.checkPermission(ctx, domain.PermissionSessionDelete, model.UserResourceOwner, model.UserID)
+	// Before 2.42.0, the resourceOwner of a session used to be the organisation of the creator.
+	// Further the (checked) users organisation id was not stored.
+	// To be able to check the permission, we need to get the user's resourceOwner in this case
+	userResourceOwner := model.UserResourceOwner
+	if model.UserID != "" && userResourceOwner == "" {
+		r := NewResourceOwnerModel(ctx, user.AggregateType, model.UserID)
```
Comment (stebenz) [inline internal/command/session.go:408]: Could move it to a separate function t just return the resource owner and the error

**Review by stebenz — APPROVED** [review]
