### PR TITLE
fix: consistent permission check on user v2

### LINKED ISSUE #7944: [Bug]: TOTP app registration fails if the requested user is not the same as the authenticated one
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

2.49.1

### Database

PostgreSQL

### Database Version

_No response_

### Describe the problem caused by this bug

When I try to [start the registration of a TOTP generator for a user](https://zitadel.com/docs/apis/resources/user_service/user-service-register-totp) using bearer token that is not belongs to the requested user, but to the IAM owner, I get the `Request user not equal to authenticated user (AUTH-Bohd2)` error.

### To reproduce

Create a new user:

```sh
curl --request POST \
  --url http://zitadel:8081/v2beta/users/human \
  --header 'Authorization: Bearer IAM_OWNER_TOKEN' \
  --header 'Content-Type: application/json' \
  --data '{
	"userId": "theUserID",
	"email": {
		"email": "theEmail@localhost",
		"isVerified": true
	},
	"profile": {
		"givenName": "theGivenName",
		"familyName": "theFamilyName"
	},
	"password": {
		"password": "theP@$$word1"
	}
}
'
```

Try to start the registration of a TOTP generator for a user:

```sh
curl --request POST \
  --url http://zitadel:8081/v2beta/users/theUserID/totp \
  --header 'Authorization: Bearer IAM_OWNER_TOKEN' \
  --header 'Content-Type: application/json' \
  --data '{}'
```

Response:

```json
{
	"code": 7,
	"message": "Request user not equal to authenticated user (AUTH-Bohd2)",
	"details": [
		{
			"@type": "type.googleapis.com/zitadel.v1.ErrorDetail",
			"id": "AUTH-Bohd2",
			"message": "Request user not equal to authenticated user"
		}
	]
}
```

### Screenshots

_No response_

### Expected behavior

To be able to start the registration of a TOTP generator for a user on behalf of the IAM owner.

### Operating System

_No response_

### Relevant Configuration

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by stebenz**
# Which Problems Are Solved

Some user v2 API calls checked for permission only on the user itself.

# How the Problems Are Solved

Consistent check for permissions on user v2 API.

# Additional Changes

None

# Additional Context

Closes #7944

### CODE REVIEW

File: internal/command/user_v2_passkey.go [hunk 1]
```diff
@@ -18,7 +17,7 @@ import (
 // RegisterUserPasskey creates a passkey registration for the current authenticated user.
 // UserID, usually taken from the request is compared against the user ID in the context.
 func (c *Commands) RegisterUserPasskey(ctx context.Context, userID, resourceOwner, rpID string, authenticator domain.AuthenticatorAttachment) (*domain.WebAuthNRegistrationDetails, error) {
-	if err := authz.UserIDInCTX(ctx, userID); err != nil {
+	if err := c.checkPermissionUpdateUser(ctx, resourceOwner, userID); err != nil {
```
Comment (livio-a) [inline internal/command/user_v2_passkey.go:20]: looks like we already have some checks in other parts (e.g. addHumanWebAuthN and createHumanTOTP) where we check for `user.credential.write` instead of `user.write`

also the linked issue  mentions TOTP but i can't find any changes in this PR related to that

Comment (stebenz) [reply internal/command/user_v2_passkey.go:20]: True, will change that.
Can't really tell you why there is TOTP mentioned, maybe it's also linked to an old ZITADEL version where there was the same topic there as well.

**Review by livio-a — COMMENTED** [review]
as just discussed.. we need to check the default permission set

File: internal/command/user_v2_passkey.go [hunk 2]
```diff
@@ -18,7 +17,7 @@ import (
 // RegisterUserPasskey creates a passkey registration for the current authenticated user.
 // UserID, usually taken from the request is compared against the user ID in the context.
 func (c *Commands) RegisterUserPasskey(ctx context.Context, userID, resourceOwner, rpID string, authenticator domain.AuthenticatorAttachment) (*domain.WebAuthNRegistrationDetails, error) {
-	if err := authz.UserIDInCTX(ctx, userID); err != nil {
+	if err := c.checkPermissionUpdateUserCredentials(ctx, resourceOwner, userID); err != nil {
```
[the remark this answers is not in the document]
Comment (stebenz) [reply internal/command/user_v2_passkey.go:20]: There are 2 changes, register passkey with permissions for another user is possible, and change password for self instead that you have to have the old password or a code (used for register for example).

**Review by eliobischof — APPROVED** [review]
