### PR TITLE
fix: correct conditions for user update after actions in post authent…

### LINKED ISSUE #5308: [Bug]: Check if action updated user fields
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

Currently actions don't check if a user has been manipulated if it already exists. If the phone number of a user is changed after the user logs in the phone number won't be changed

### To reproduce

1. create an action
2. add the action to the post authentication flow
3. the phone won't be changed

### Screenshots

_No response_

### Expected behavior

The changes of actions should be applied to the user

### Version

2.20.1

### Operating System

_No response_

### Relevant Configuration

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by stebenz**
…ication

Correct conditions on when the user gets updated through actions in post-authentication, with an added boolean for checking if anything changed in the actions.

```[tasklist]
### Definition of Ready
- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.
```

closes #5308

### CODE REVIEW

File: internal/api/ui/login/custom_action.go [hunk 1]
```diff
@@ -23,49 +23,60 @@ func (l *Login) runPostExternalAuthenticationActions(
 	httpRequest *http.Request,
 	idpUser idp.User,
 	authenticationError error,
-) (*domain.ExternalUser, error) {
+) (*domain.ExternalUser, bool, error) {
 	ctx := httpRequest.Context()
+	change := false
```
Comment (livio-a) [inline internal/api/ui/login/custom_action.go:28]: i think we should name the return values and (as you already mentioned) the externalUser as return value is not necessary, but does not have to be removed now
for the `change` i'd suggest to rename it to `userChanged` or something like that

**Review by livio-a — CHANGES_REQUESTED** [review]
the additional return value seems not to be handled in the ldap provider

File: internal/api/ui/login/custom_action.go (hunk 1 above)
Comment (stebenz) [reply internal/api/ui/login/custom_action.go]: renamed to userChanged and used it as named return value, also corrected the handling in the ldap provider

**Review by livio-a — APPROVED** [review]
