### PR TITLE
fix(console): Add login v2 url to identity providers

### LINKED ISSUE #10461: [Bug]: Incorrect redirect_uri being passed to Microsoft
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

ghcr.io/zitadel/zitadel:latest

### Database

PostgreSQL

### Database Version

postgres:17-alpine

### Describe the problem caused by this bug

I set up the Microsoft Identity Provider and added the `redirect_uri` as presented in the Zitadel UI of

http://localhost:8081/ui/login/login/externalidp/callback

Image

However when I selected the provider on the login screen I noticed that is used a different redirect_uri in the url it passed

http://localhost:8080/idps/callback

Image

This is obviously incorrect and leads to failures going forward

> AADSTS50011: The redirect URI 'http://localhost:8080/idps/callback' specified in the request does not match the redirect URIs configured for the application '...<client_id>...'

### To reproduce

Follow the instructions to setup Microsoft Entra

https://zitadel.com/docs/guides/integrate/identity-providers/azure-ad-oidc

Try to login

### Screenshots

_No response_

### Expected behavior

The correct redirect_uri should be supplied to Microsoft

### Operating System

Mac Sequoia 15.6

### Relevant Configuration

This is the standalone set up using the docker-compose.yml file from https://zitadel.com/docs/self-hosting/deploy/compose

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by conblem**
# Which Problems Are Solved

When using login V2 the Callback URL for an Identity Provider is different. When following the guideance in the console and using Login V2 users will use the wrong callback url.

grafik

# How the Problems Are Solved
I have added the correct Login V2 url to the identity providers and updated our docs.

grafik

# Additional Changes
Small refactorings and porting some components over to ChangeDetection OnPush

# Additional Context

Replace this example with links to related issues, discussions, discord threads, or other sources with more context.
Use the Closing #issue syntax for issues that are resolved with this PR.
- Closes #10461

### CODE REVIEW

File: console/src/app/modules/card/card.component.ts [hunk 1]
```diff
@@ -1,26 +1,15 @@
-import { animate, style, transition, trigger } from '@angular/animations';
-import { Component, Input } from '@angular/core';
+import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
 
 @Component({
   selector: 'cnsl-card',
   templateUrl: './card.component.html',
   styleUrls: ['./card.component.scss'],
-  animations: [
```
Comment (conblem) [inline console/src/app/modules/card/card.component.ts:8]: I have never worked with these animations but as far as I am aware the animation was not actually used. Reviewer please check again

File: console/src/app/modules/info-section/info-section.component.html [hunk 2]
```diff
@@ -1,17 +1,15 @@
 <div
   class="info-section-row"
   [ngClass]="{
-    info: type === 'INFO',
-    warn: type === 'WARN',
-    alert: type === 'ALERT',
-    success: type === 'SUCCESS',
```
Comment (conblem) [inline console/src/app/modules/info-section/info-section.component.html:7]: I was not able to find any usage for the success case

**Comment by conblem** [comment]
I haven't found any mention of the callback url's in the doc's so I just changed it for the linkedin example. Not sure if im missing something here.

File: console/src/app/modules/card/card.component.ts (hunk 1 above)
Comment (peintnermax) [reply console/src/app/modules/card/card.component.ts:8]: can you remove the openclose animation of the `org-create.component.ts` as well please?

File: console/src/app/modules/card/card.component.html [hunk 3]
```diff
@@ -1,4 +1,4 @@
-<div class="card" [ngClass]="{ nomargin: nomargin, stretch: stretch, warn: warn }" data-e2e="app-card">
+<div class="card" [ngClass]="{ nomargin: nomargin, warn: warn }" data-e2e="app-card">
```
Comment (peintnermax) [inline console/src/app/modules/card/card.component.html:1]: since you have removed the stretch property, can you remove the styling of the component.scss as well?

**Review by peintnermax — APPROVED** [review]
