### PR TITLE
fix(actionsV2): executing request/response type for 'all' condition

### LINKED ISSUE #10895: Action V2: condition all doesn't work for request and response types
Actions set to run on any request or on any response are never executed.

How to reproduce:
1. Create target (with any type)
2. Create action of type request or response and use condition "all" and use the previously created target
3. Call any endpoint in Zitadel

After changing the condition to the service or explicit method, the target it called.

This looks like an issue from the refactoring of #10564 .

### PR DESCRIPTION
**Pull request by grvijayan**
# Which Problems Are Solved

In actions v2, when the condition `all` is chosen, or a specific method is not specified for a service action, the actions are not executed. 

# How the Problems Are Solved

The wildcard suffix `.*` is used only for event groups. As global `requests`, `responses` or `services with no specified method` do not have this suffix, they were bypassing the prefix-match check. This check therefore does not apply to action types other than `event` 

This issue is fixed by removing the `e.ID == "event"` condition when prefix-matching execution IDs to not exclude other action types (`request`, `response`, etc).

# Additional Changes
N/A

# Additional Context

- Closes #10895

### CODE REVIEW

**Comment by livio-a** [comment]
@grvijayan The "all" condition works for events but not for requests or responses. I rechecked and it also doesn't work when selecting a service. It only does when choosing the endpoint.

File: internal/execution/target/router_test.go [hunk 1]
```diff
@@ -94,7 +112,7 @@ func TestBinarySearchRouter_GetEventBestMatch(t *testing.T) {
 			name:    "event group match",
 			targets: testTargets[1:],
 			args: args{
-				id: "event/foo.bar.baz",
+				id: "event/foo.baz",
```
Comment (grvijayan) [inline internal/execution/target/router_test.go:115]: to clarify: before current changes, why was `event/foo.bar.baz` matching `eventGroupTarget` (`event/foo.*`) when there's a better match `eventMatchTarget` (`event/foo.bar`)

Comment (livio-a) [reply internal/execution/target/router_test.go:115]: I'm also just guessing, but I imagine the initial idea was to explicitly target all events of a group by setting the wildcard. In the actual implementation/events there's probably not really a case where this could happen and it's either en exact match on a explicit event or a wildcard match on a group, but not a wird card match on an event
