### PR TITLE
fix(login): refactor SAML Post Flow to bypass cookie limits, fix SAML SP post

### LINKED ISSUE #10759: [Bug]: SAML IdP: With Use new Login UI enabled, POST-initiated AuthnRequest redirects to ACS without SAMLResponse/RelayState
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

4.2.2

### Database

None

### Database Version

_No response_

### Describe the problem caused by this bug

When the SP initiates SSO using **HTTP-POST** binding for the `AuthnRequest`, the flow succeeds through authentication but finishes with an HTTP redirect to the ACS URL **without** posting the expected `SAMLResponse` and `RelayState`.
This breaks POST-binding integrations and drops application state that depends on RelayState.

- Works with HTTP-Redirect initiated requests ✅

- Works with old Login UI (both bindings) ✅

- Fails only when Use new Login UI is turned on and the SP uses HTTP-POST binding ❌

### To reproduce

1. In ZITADEL Console, create/configure a **SAML application** and enable **Use new Login UI**.
2. Configure your **Service Provider** (SP) to initiate SSO using **HTTP-POST** binding for the `AuthnRequest` to ZITADEL’s SSO endpoint.
3. Start the login from the SP.
4. Authenticate successfully in ZITADEL’s new Login UI.
5. Observe the final browser interaction to the ACS URL:

   * The browser is **redirected (GET)** to the ACS URL.
   * There is **no form POST** containing `SAMLResponse` and `RelayState`.

Control tests:
6\. Repeat with SP initiating via **HTTP-Redirect** binding → **Works** (ACS receives a POST with `SAMLResponse` and `RelayState`).
7\. Toggle off **Use new Login UI** and retry with **HTTP-POST** binding → **Works**.

### Screenshots

Turn on the "Use new Login UI" checkbox in the SAML app:
Image

### Expected behavior

After successful authentication, ZITADEL should **POST** to the ACS URL with a form containing:

- `SAMLResponse`

- `RelayState` (if provided by the SP)

### Operating System

_No response_

### Relevant Configuration

_No response_

### Additional Context

_No response_

### LINKED ISSUE #10816: [Bug]: Login v2: External SAML IdP with SAML_BINDING_POST fails with 404 → “SAML form data not found”
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

4.2.2

### Database

None

### Database Version

_No response_

### Describe the problem caused by this bug

When using **Login v2**, configuring an **external SAML Identity Provider** with **Binding = `SAML_BINDING_POST`** breaks the sign-in flow. Clicking the SAML connection on the Login v2 page triggers a GET to `/ui/v2/login/saml-post?...` which returns **404** with the body **“SAML form data not found.”**
This prevents using POST binding for external SAML IdPs in Login v2.

### Impact

* Users cannot start SAML authentication via **POST binding** in Login v2.
* Blocks orgs that require POST due to SP/IdP policy or compliance.

### To reproduce

1. In ZITADEL, add an **External SAML** IdP (any provider).
2. Set **Binding** to **`SAML_BINDING_POST`**.
3. Ensure the application uses **Login v2**.
4. Start an OIDC login and select the SAML connection.
5. Observe the network request to:

   * `GET /ui/v2/login/saml-post?url=<IdP SSO URL>&id=<uuid>`
6. Response is **404** with text **“SAML form data not found.”**&#x20;

### Screenshots

_No response_

### Expected behavior

Login v2 should correctly initiate the SAML POST flow (render/submit an auto-posting HTML form to the IdP SSO URL with the appropriate parameters) and proceed to the IdP.

### Actual Behavior

* Browser performs a **GET** to `/ui/v2/login/saml-post?...`
* Server responds **404** with **“SAML form data not found.”**&#x20;

### Operating System

_No response_

### Relevant Configuration

_No response_

### Additional Context

* Using **`SAML_BINDING_REDIRECT`** instead of POST works.

### PR DESCRIPTION
**Pull request by peintnermax**
Closes #10816
Closes #10759

# Which Problems Are Solved

This PR refactors the SAML Post binding flow to address issues with payloads exceeding browser cookie size limits (typically ~4KB). Previously, the SAML form data was serialized into a cookie, and the user was redirected to an intermediate /saml-post page to render the form. This approach failed for large SAML assertions.

# How the Problems Are Solved

The new implementation bypasses cookies entirely for the payload transfer. Server actions now return the form data directly to the client, which immediately renders and submits the form.

- Direct Data Transfer: Updated `startIdentityProviderFlow` to return an object { url, fields } instead of a redirect URL when the next step is formData.
- Server Actions: Updated redirectToIdp, sendLoginname, and completeAuthFlow to propagate this samlData object to the client.
- Client-Side Auto-Submission: Added a new AutoSubmitForm component that renders a hidden form with the provided fields and automatically submits it to the IdP on mount.

### CODE REVIEW

File: apps/login/src/components/login-otp.tsx [hunk 1]
```diff
@@ -214,68 +209,71 @@ export function LoginOTP({ host, loginName, sessionId, requestId, organization,
...
+            <div className="flex flex-row">
+              <span className="mr-auto flex-1 text-left">
+                <Translated i18nKey="verify.noCodeReceived" namespace="otp" />
+              </span>
+              <button
+                aria-label="Resend OTP Code"
+                disabled={loading}
+                type="button"
+                className="ml-4 cursor-pointer text-primary-light-500 hover:text-primary-light-400 disabled:cursor-default disabled:text-gray-400 dark:text-primary-dark-500 hover:dark:text-primary-dark-400 dark:disabled:text-gray-700"
+                onClick={() => {
```
Comment (conblem) [inline apps/login/src/components/login-otp.tsx]: async await and try catch finally might be a bit more readable

File: apps/login/src/components/login-otp.tsx [hunk 2]
```diff
@@ -214,68 +209,71 @@ export function LoginOTP({ host, loginName, sessionId, requestId, organization,
...
+        <div className="mt-8 flex w-full flex-row items-center">
+          <BackButton data-testid="back-button" />
+          <span className="flex-grow"></span>
+          <Button
+            type="submit"
+            className="self-end"
+            variant={ButtonVariants.Primary}
+            disabled={loading || !formState.isValid}
+            onClick={handleSubmit((e) => {
+              setCodeAndContinue(e, organization);
```
Comment (conblem) [inline apps/login/src/components/login-otp.tsx]: why is organization passed as a parameter to setCodeAndContinue if its already in scope? we should probably also use useCallback for setCodeAndContinue

File: apps/login/src/lib/server/flow-initiation.ts [hunk 3]
```diff
@@ -99,7 +97,9 @@ export async function handleOIDCFlowInitiation(params: FlowInitiationParams): Pr
       const matched = IDP_SCOPE_REGEX.exec(idpScope);
       idpId = matched?.[1] ?? "";
 
-      const identityProviders = await getActiveIdentityProviders({ serviceConfig, orgId: organization ? organization : undefined,
+      const identityProviders = await getActiveIdentityProviders({
```
Comment (conblem) [inline apps/login/src/lib/server/flow-initiation.ts:101]: const { identityProviders } = await getActiveIdentityProviders(....)

File: apps/login/src/lib/server/flow-initiation.ts [hunk 4]
```diff
@@ -132,17 +132,42 @@ export async function handleOIDCFlowInitiation(params: FlowInitiationParams): Pr
...
+        if (!response || !response.url) {
           return NextResponse.json({ error: "Could not start IDP flow" }, { status: 500 });
         }
 
+        if (response.fields) {
+          const hiddenInputs = Object.entries(response.fields)
+            .map(([key, value]) => `<input type="hidden" name="${key}" value="${value}" />`)
+            .join("\n");
+
+          const html = `
```
Comment (conblem) [inline apps/login/src/lib/server/flow-initiation.ts:153]: we should definetly sanitize the html even if the inputs are safe id rather do it unnecessarily than not do it.

File: apps/login/src/components/login-otp.tsx (hunk 1 above)
Comment (peintnermax) [reply apps/login/src/components/login-otp.tsx]: done

File: apps/login/src/lib/server/flow-initiation.ts (hunk 3 above)
Comment (peintnermax) [reply apps/login/src/lib/server/flow-initiation.ts:101]: The function does not return { identityProviders }. what is your intention to change?

File: apps/login/src/lib/server/flow-initiation.ts (hunk 4 above)
Comment (peintnermax) [reply apps/login/src/lib/server/flow-initiation.ts:153]: I've implemented escape-html and url, key and value properties are now sanitized

File: apps/login/src/components/login-otp.tsx (hunk 2 above)
Comment (peintnermax) [reply apps/login/src/components/login-otp.tsx]: you are right. this is cleaned up right now

Comment (peintnermax) [reply apps/login/src/components/login-otp.tsx]: setCodeAndContinue is a simple event handler so useCallback is not required. It is useful for `updatesessionforchallenge`. Implemented it there.

File: apps/login/src/lib/server/password.ts [hunk 5]
```diff
@@ -368,45 +370,37 @@ export async function sendPassword(command: UpdateSessionCommand): Promise<{ err
...
-  // Regular flow (no requestId) - return URL for client-side navigation
-
-  const result = await completeFlowOrGetUrl(
-    {
-      loginName: session.factors.user.loginName,
-      organization: session.factors?.user?.organizationId,
-    },
-    loginSettingsByUser?.defaultRedirectUri,
-  );
+  console.log("Password auth: Result:", result);
```
[the remark this answers is not in the document]
Comment (peintnermax) [reply apps/login/src/lib/server/password.ts]: removed the log

File: apps/login/src/lib/server/idp.ts [hunk 6]
```diff
@@ -81,6 +83,10 @@ export async function redirectToIdp(prevState: RedirectToIdpState, formData: For
     redirect(response.redirect);
   }
 
+  if (response && "samlData" in response && response?.samlData) {
+    return { samlData: response.samlData };
+  }
+
   return { error: "Unexpected response from IDP flow" };
```
[the remark this answers is not in the document]
Comment (peintnermax) [reply apps/login/src/lib/server/idp.ts:94]: done

File: apps/login/src/lib/client.ts [hunk 7]
```diff
@@ -43,7 +43,7 @@ function goToSignedInPage(
 export async function completeFlowOrGetUrl(
   command: FinishFlowCommand & { organization?: string },
   defaultRedirectUri?: string,
-): Promise<{ redirect: string } | { error: string }> {
+): Promise<{ redirect: string } | { error: string } | { samlData: { url: string; fields: Record<string, string> } }> {
   console.log("completeFlowOrGetUrl called with:", command, "defaultRedirectUri:", defaultRedirectUri);
```
[the remark this answers is not in the document]
Comment (peintnermax) [reply apps/login/src/lib/client.ts:47]: removed logs of results

File: apps/login/src/lib/server/password.ts [hunk 8]
```diff
@@ -368,45 +370,37 @@ export async function sendPassword(command: UpdateSessionCommand): Promise<{ err
     return mfaFactorCheck;
   }
 
+  let result;
```
[the remark this answers is not in the document]
Comment (peintnermax) [reply apps/login/src/lib/server/password.ts]: applied

File: apps/login/src/components/auto-submit-form.tsx [hunk 9]
```diff
@@ -0,0 +1,29 @@
...
+};
+
+export function AutoSubmitForm({ url, fields }: Props) {
+  const formRef = useRef<HTMLFormElement>(null);
+
+  useEffect(() => {
+    if (formRef.current) {
+      formRef.current.submit();
+    }
+  }, []);
```
[the remark this answers is not in the document]
Comment (peintnermax) [reply apps/login/src/components/auto-submit-form.tsx:17]: the mounting is dependant on the properties and they are not expected to change
