### PR TITLE
fix: overflow of aggregates filter in console, add missing aggregates translations, update yarn lock

### LINKED ISSUE #6874: [Bug]: Console event viewer filter aggregate type cut off
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

v2.40.3

### Describe the problem caused by this bug

Makes it difficult to select the correct aggregate type 

Screenshot 2023-11-07 at 09 34 13

### To reproduce

1. https://b2b-demo-rbxajm.zitadel.cloud/ui/console/events
2. Press F
3. Click Aggregate Type dropdown

### Screenshots

_No response_

### Expected behavior

Aggregate types are readable

### Operating System

Chrome 118.0.5993.117

### Relevant Configuration

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by peintnermax**
This PR fixes an overflow of the aggregate types filter in the events table and adds missing translations
Closes #6874 

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

File: console/src/app/modules/accounts-card/accounts-card.component.ts [hunk 1]
```diff
@@ -61,7 +61,8 @@ export class AccountsCardComponent implements OnInit {
   public selectNewAccount(): void {
     const configWithPrompt: Partial<AuthConfig> = {
       customQueryParams: {
-        prompt: 'login',
+        prompt: 'create',
+        scope: 'openid profile email urn:zitadel:iam:org:domain:primary:maxgitlab1.zitadel.app',
```
Comment (eliobischof) [inline console/src/app/modules/accounts-card/accounts-card.component.ts:65]: maxgitlab1.zitadel.app?

**Review by eliobischof — CHANGES_REQUESTED** [review]

File: console/src/app/modules/accounts-card/accounts-card.component.ts (hunk 1 above)
Comment (peintnermax) [reply console/src/app/modules/accounts-card/accounts-card.component.ts]: removed

**Review by eliobischof — APPROVED** [review]
