### PR TITLE
fix(login): mfa prompt UI improvements, fix register field validation, email validation

### LINKED ISSUE #4613: Username overflow in login ui
**Describe the bug**
The username overflows the displayed field for long, but allowed usernames.

**To Reproduce**
Create a user with long username (eg, mpa+uxtest20221026@mpa+uxtest20221026.zitadel.cloud) and complete user initialization and login.

- `/ui/login/init`
- `/ui/login/password`
- `/ui/login/mfa/prompt`
- `/ui/login/loginname`
- ...

**Expected behavior**
UI to respond to long usernames.

**Screenshots**

Screenshot 2022-10-26 at 09 25 40

**Desktop (please complete the following information):**
MacOS, Chrome

**Additional context**

### LINKED ISSUE #4648: Confusing behaviour in the 2-Factor Setup screen
**Describe the bug**
It is not clear that an option needs to be selected (we received complaints that nothing happens when clicking "next").
Also, the "skip" and "next" buttons change the cursor to a finger pointer, but the MFA options don't (it is not clear that they are clickable).

Possible solutions:
- preselect one of the two. In that case which one is selected should be clearly visible, currently the blue square is a bit hard to see. Also, the fact that the authenticator app section is colored as opposed to the other section might be misleading (at a first glance it looks like the colored one is the selected one).
- disable the "next" button unless on option is selected (displaying the reason on hover)
- display an error telling the user that they have to make a selection

**Screenshots**
Screenshot 2022-11-02 at 10 58 18

**Additional context**
ZITADEL Cloud 2.10.0

### LINKED ISSUE #4706: [Bug]: registration ui breaks with long custom-domains
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

registration and logn ui break with long custom-domains

### To reproduce

1. create ZITADEL Org
2. use looooong custom-domain
3. open register or login-ui

### Screenshots

image

### Expected behavior

no break

### Version

_No response_

### Operating System

_No response_

### Relevant Configuration

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by peintnermax**
Closes #4648
Closes #4613
Closes #4706

### CODE REVIEW

File: internal/api/ui/login/static/resources/scripts/change_password_check.js [hunk 1]
```diff
@@ -1,16 +1,25 @@
...
+  );
+  let pwNewConfirmationValue = pwNewConfirmation.value;
 
-    if (ComplexityPolicyCheck(policyElement, pwNew, pwNewConfirmation) === false) {
-        policyElement.setAttribute("color", "warn");
-        return false;
-    } else {
-        policyElement.setAttribute("color", "primary");
-    }
+  if (ComplexityPolicyCheck(pwNew) === false) {
```
Comment (adlerhurst) [inline internal/api/ui/login/static/resources/scripts/change_password_check.js:9]: is it normal to check bools in js this way? I'm used to check in this fashion: `if (! ComplexityPolicyCheck(...))`

File: internal/api/ui/login/static/resources/scripts/init_password_check.js [hunk 2]
```diff
@@ -1,14 +1,15 @@
...
-    let pwNewConfirmation = document.getElementById("passwordconfirm").value;
+  let pwNew = document.getElementById("password");
+  let pwNewValue = pwNew.value;
+  const pwNewConfirmation = document.getElementById("passwordconfirm");
+  let pwNewConfirmationValue = pwNewConfirmation.value;
 
-    if (ComplexityPolicyCheck(policyElement, pwNew, pwNewConfirmation) === false) {
-        return false;
-    }
+  if (ComplexityPolicyCheck(pwNew) === false) {
```
Comment (adlerhurst) [inline internal/api/ui/login/static/resources/scripts/init_password_check.js:7]: same as comment above

File: internal/api/ui/login/static/resources/scripts/password_policy_check.js [hunk 3]
```diff
@@ -1,77 +1,71 @@
...
+  let numberRegex = passwordElement.dataset.hasNumber;
+  let symbolRegex = passwordElement.dataset.hasSymbol;
 
-    let invalid = 0;
+  let invalid = 0;
 
-    let minlengthelem = document.getElementById('minlength');
-    if (pwNew.length >= minLength) {
-        ValidPolicy(minlengthelem);
+  let minlengthelem = document.getElementById("minlength");
```
Comment (adlerhurst) [inline internal/api/ui/login/static/resources/scripts/password_policy_check.js:10]:
```suggestion
  let minLengthElem = document.getElementById("minlength");
```

File: internal/api/ui/login/static/resources/scripts/password_policy_check.js [hunk 4]
```diff
@@ -1,77 +1,71 @@
...
-        }
+  }
+  let number = document.getElementById("number");
+  if (numberRegex !== "") {
+    if (RegExp(numberRegex).test(passwordElement.value)) {
+      ValidPolicy(number);
+    } else {
+      InvalidPolicy(number);
+      invalid++;
     }
```
Comment (adlerhurst) [inline internal/api/ui/login/static/resources/scripts/password_policy_check.js:42]: IMO the code to check the policy is the same for all policies. If so please reuse the same logic instead of copy pasta

File: internal/api/ui/login/static/resources/scripts/register_check.js [hunk 5]
```diff
@@ -1,16 +1,25 @@
...
+  }
 
-    return pwNew == pwNewConfirmation;
+  if (pwNewValue !== pwNewConfirmationValue && pwNewConfirmationValue !== "") {
+    pwNewConfirmation.setAttribute("color", "warn");
+  } else {
+    pwNewConfirmation.setAttribute("color", "primary");
+  }
+
+  return pwNewValue == pwNewConfirmationValue;
```
Comment (adlerhurst) [inline internal/api/ui/login/static/resources/scripts/register_check.js:22]: feels like the same code like in change_password_check.js

File: internal/api/ui/login/static/resources/scripts/init_password_check.js (hunk 2 above)
Comment (adlerhurst) [reply internal/api/ui/login/static/resources/scripts/init_password_check.js:7]: and the checks look like the same as in change_password_check.js

File: internal/api/ui/login/static/resources/scripts/change_password_check.js (hunk 1 above)
Comment (peintnermax) [reply internal/api/ui/login/static/resources/scripts/change_password_check.js:9]: 👍

File: internal/api/ui/login/static/resources/scripts/init_password_check.js (hunk 2 above)
Comment (peintnermax) [reply internal/api/ui/login/static/resources/scripts/init_password_check.js]: I'd not use a script for multiple pages as this could be not comprehensible for additional changes..

File: internal/api/ui/login/static/resources/scripts/password_policy_check.js (hunk 4 above)
Comment (peintnermax) [reply internal/api/ui/login/static/resources/scripts/password_policy_check.js:42]: same above

File: internal/api/ui/login/static/resources/scripts/password_policy_check.js [hunk 6]
```diff
@@ -1,77 +1,71 @@
...
+  let invalid = 0;
 
-    let minlengthelem = document.getElementById('minlength');
-    if (pwNew.length >= minLength) {
-        ValidPolicy(minlengthelem);
+  let minLengthElem = document.getElementById("minlength");
+  if (passwordElement.value.length >= minLength) {
+    ValidPolicy(minlengthelem);
+  } else {
+    InvalidPolicy(minlengthelem);
```
Comment (livio-a) [inline internal/api/ui/login/static/resources/scripts/password_policy_check.js:14]:
```suggestion
    ValidPolicy(minLengthElem);
  } else {
    InvalidPolicy(minLengthElem);
```

**Review by livio-a — CHANGES_REQUESTED** [review]
as discussed together the input seems ok, but the confirmation is still considered as false
image

**Comment by peintnermax** [comment]
> ComplexityPolicyCheck

This is fixed now 👍

File: internal/api/ui/login/static/resources/scripts/email.js [hunk 7]
```diff
@@ -0,0 +1,16 @@
+const pattern = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
```
[the remark this answers is not in the document]
Comment (fforootd) [reply internal/api/ui/login/static/resources/scripts/email.js:1]: @peintnermax FYI CodeQL is not really happy 😁

[the remark this answers is not in the document]
Comment (fforootd) [reply internal/api/ui/login/static/resources/scripts/email.js:1]: @peintnermax FYI CodeQL is not really happy 😁

[the remark this answers is not in the document]
Comment (peintnermax) [reply internal/api/ui/login/static/resources/scripts/email.js]: just updated it to another one 👍

File: internal/api/ui/login/static/resources/scripts/email.js [hunk 8]
```diff
@@ -0,0 +1,18 @@
+// according to RFC 2822 https://www.rfc-editor.org/rfc/rfc2822
+const pattern =
+  /(?:[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/;
```
[the remark this answers is not in the document]
Comment (peintnermax) [reply internal/api/ui/login/static/resources/scripts/email.js:3]: @livio-a what do you think.. DDoS is not really a concern as the code is executed in the browser.. I would merge this.. the last regex considers [RFC 2822](https://www.rfc-editor.org/rfc/rfc2822) format. Or what would you do?

**Review by livio-a — APPROVED** [review]
