### PR TITLE
fix(api): use organization instead of organisation

### LINKED ISSUE #6604: [Bug]: Typo in session API response object - "organisation"
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.37.1

### Describe the problem caused by this bug

There is a typo in word "organization" in API https://zitadel.com/docs/apis/resources/session_service/session-service-get-session, response object, path `session/factors/user/organisationId`. Should be `organizationId".
Besides, there is a number of other places in code where this typo "organisation" exists.

### To reproduce

Search codebase, a number of same typos exist. In this API too: https://zitadel.com/docs/apis/resources/session_service/session-service-get-session

### Screenshots

_No response_

### Expected behavior

No typos in "organization" word :)

### Operating System

_No response_

### Relevant Configuration

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by livio-a**
- renames organisation to organization, where possible
- where it would be a breaking change, a new field is added and the current deprecated (to be removed before GA with https://github.com/zitadel/zitadel/issues/6718)

closes #6604 

### Definition of Ready

- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [x] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [x] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

File: internal/api/grpc/server/middleware/auth_interceptor.go [hunk 1]
```diff
@@ -47,11 +42,38 @@ func authorize(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo,
...
+	}
+	// check if the deprecated organisation is used.
+	// to be removed before going GA (https://github.com/zitadel/zitadel/issues/6718)
+	id = o.OrganisationFromRequest().ID
+	domain = o.OrganisationFromRequest().Domain
+	if id != "" || domain != "" {
+		return id, domain
+	}
+	return orgID, domain
+}
```
Comment (muhlemmer) [inline internal/api/grpc/server/middleware/auth_interceptor.go:64]: As `OrganizationFromRequest()` / `OrganisationFromRequest()` return a pointer `*Organizaion`, shouldn't there be a `nil` check here? Even better, can't we just check for the existence of one or the other based on `nil` check then return the orgID if it was present:


```suggestion
	org := o.OrganizationFromRequest()
	// check if the deprecated organisation is used.
	// to be removed before going GA (https://github.com/zitadel/zitadel/issues/6718)
	if org == nil {
		org = o.OrganisationFromRequest()
	}
	if org != nil {
		if org.ID != "" {
			return org.ID, org.Domain
		}
		return orgID, org.Domain
	}
	return orgID, ""
```

Comment (muhlemmer) [reply internal/api/grpc/server/middleware/auth_interceptor.go:64]: I see now that the implementation of the above methods actually never return `nil`. So not sure if the comment is still valid.

Best preactice would be a `nil` check. But then the implementation should also return a `nil` for either case if it wasn't set.

File: proto/zitadel/user/v2beta/user_service.proto [hunk 2]
```diff
@@ -655,7 +655,9 @@ message AddHumanUserRequest{
       example: "\"minnie-mouse\"";
     }
   ];
+  // deprecated: use organization (if both are set, organization will take precedence)
   zitadel.object.v2beta.Organisation organisation = 3;
+  zitadel.object.v2beta.Organization organization = 11;
```
Comment (muhlemmer) [inline proto/zitadel/user/v2beta/user_service.proto:660]: The deprecation note is not shown in the [API documentation](https://docs-g0jlf8yty-zitadel.vercel.app/docs/apis/resources/user_service/user-service-add-human-user):

It does for the session response object somehow.

image

**Review by muhlemmer — CHANGES_REQUESTED** [review]

**Review by muhlemmer — APPROVED** [review]
