### PR TITLE
fix(idp): make external id check case insensitive

### LINKED ISSUE #10457: [Bug]: Errors.User.ExternalIDP.AlreadyExists caused by case sensitive external user IDs
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

_No response_

### Database

None

### Database Version

_No response_

### Describe the problem caused by this bug

Zitadel fails to authenticate existing users via SAML when the Subject Name ID (external user ID) in the SAML response has different character casing compared to previous logins. The system appears to perform case-sensitive matching on the Subject Name ID, which prevents automatic user linking by username or email address and results in the following error:

```
Errors.User.ExternalIDP.AlreadyExists (V3-DKcYh)
```

Image

Example:

- Initial login: Subject Name ID = `myuserid`
- Subsequent login: Subject Name ID = `Myuserid`
- Result: Authentication failure despite being the same user

**The impact on our operation is critical, as we cannot predict when clients are going to make updates to the external user IDs of existing users.**

### To reproduce

1. Create a new organization in Zitadel
2. Ensure the organization allows external user logins in the "Login Behavior and Security
" settings of the org
3. Create a new configuration in a SAML IDP of your preference (we used Okta to reproduce the issue)
4. Configure a new SAML IDP for that org with the following settings:
    1. Configure the metadata obtained from the SAML IDP
    2. Enable: Automatic creation and automatic update
    3. Disable: Account creation allowed (manually), Account linking allowed
    4. Set "Check for existing Username" for "Determines whether an identity will be prompted to be linked to an existing account"
5. Add a post external authentication action to the org to map the attributes sent by the SAML IDP
6. Log in with the SAML IDP so a new user record is created
7. In the external SAML IDP, modify the user's Subject NameID to use different character casing
    E.g.: Change `myuserid` to `Myuserid`
8. Attempt to log in again via SAML IDP
9. The `Errors.User.ExternalIDP.AlreadyExists (V3-DKcYh)` should appear

### Screenshots

_No response_

### Expected behavior

When auto-linking by username or email address is enabled, Zitadel should either:

1. Perform case-insensitive matching against the external user ID of existing identity provider links
2. Create a new identity provider link with the new user external ID

### Operating System

_No response_

### Relevant Configuration

_No response_

### Additional Context

Relates to https://github.com/zitadel/zitadel/issues/10090

### PR DESCRIPTION
**Pull request by livio-a**
# Which Problems Are Solved

When searching for an existing external userID from an IdP response, the comparison is case sensitive. This can lead to issues esp. when using SAML, since the `NameID`'s value case could change. The existing user would not be found and the login would try to create a new one, but fail since the uniqueness check of IdP ID and external userID is not case insensitive.

# How the Problems Are Solved

Search case insensitive for external useriDs.

# Additional Changes

None

# Additional Context

- closes #10457, #10387
- backport to v3.x

### CODE REVIEW

File: internal/query/idp_user_link.go [hunk 1]
```diff
@@ -178,7 +178,7 @@ func NewIDPUserLinksResourceOwnerSearchQuery(value string) (SearchQuery, error)
 }
 
 func NewIDPUserLinksExternalIDSearchQuery(value string) (SearchQuery, error) {
-	return NewTextQuery(IDPUserLinkExternalUserIDCol, value, TextEquals)
+	return NewTextQuery(IDPUserLinkExternalUserIDCol, value, TextEqualsIgnoreCase)
```
Comment (adlerhurst) [inline internal/query/idp_user_link.go:181]: Should we add an index in the database?
