### PR TITLE
fix(metrics): incorrect mapping of grpc status codes in the `grpc_server_grpc_status_code_total` metric

### LINKED ISSUE #10884: [Bug]: Incorrect metrics for grpc_server_grpc_status_code_total
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v4.3.2

### Database

PostgreSQL

### Database Version

17

### Describe the problem caused by this bug

It looks like there’s a bug in collecting data for the grpc_server_grpc_status_code_total counter.

After starting the example Zitadel instance with Docker Compose and opening the login page, the `/debug/metrics` endpoint shows the following records:
```
# HELP grpc_server_grpc_status_code_total Grpc status code counter
# TYPE grpc_server_grpc_status_code_total counter
grpc_server_grpc_status_code_total{grpc_method="/zitadel.oidc.v2.OIDCService/GetAuthRequest",return_code="500"} 1
grpc_server_grpc_status_code_total{grpc_method="/zitadel.org.v2.OrganizationService/ListOrganizations",return_code="500"} 2
grpc_server_grpc_status_code_total{grpc_method="/zitadel.session.v2.SessionService/CreateSession",return_code="500"} 1
grpc_server_grpc_status_code_total{grpc_method="/zitadel.session.v2.SessionService/GetSession",return_code="500"} 2
grpc_server_grpc_status_code_total{grpc_method="/zitadel.session.v2.SessionService/ListSessions",return_code="500"} 1
grpc_server_grpc_status_code_total{grpc_method="/zitadel.settings.v2.SettingsService/GetActiveIdentityProviders",return_code="500"} 2
grpc_server_grpc_status_code_total{grpc_method="/zitadel.settings.v2.SettingsService/GetBrandingSettings",return_code="500"} 3
grpc_server_grpc_status_code_total{grpc_method="/zitadel.settings.v2.SettingsService/GetHostedLoginTranslation",return_code="500"} 3
grpc_server_grpc_status_code_total{grpc_method="/zitadel.settings.v2.SettingsService/GetLoginSettings",return_code="500"} 7
grpc_server_grpc_status_code_total{grpc_method="/zitadel.settings.v2.SettingsService/GetSecuritySettings",return_code="500"} 1
grpc_server_grpc_status_code_total{grpc_method="/zitadel.user.v2.UserService/ListAuthenticationMethodTypes",return_code="500"} 1
grpc_server_grpc_status_code_total{grpc_method="/zitadel.user.v2.UserService/ListUsers",return_code="500"} 1
```
I suspect there’s a bug that incorrectly interprets some gRPC status codes (https://grpc.io/docs/guides/status-codes/) as 500.

When I continue and enter my password so that the Console App opens, new records appear with `return_code="200"`:
```
grpc_server_grpc_status_code_total{grpc_method="/zitadel.admin.v1.AdminService/ListMilestones",return_code="200"} 1
grpc_server_grpc_status_code_total{grpc_method="/zitadel.auth.v1.AuthService/GetMyLabelPolicy",return_code="200"} 2
grpc_server_grpc_status_code_total{grpc_method="/zitadel.auth.v1.AuthService/GetMyPrivacyPolicy",return_code="200"} 2
grpc_server_grpc_status_code_total{grpc_method="/zitadel.auth.v1.AuthService/GetMyUser",return_code="200"} 1
grpc_server_grpc_status_code_total{grpc_method="/zitadel.auth.v1.AuthService/ListMyProjectOrgs",return_code="200"} 4
grpc_server_grpc_status_code_total{grpc_method="/zitadel.auth.v1.AuthService/ListMyZitadelPermissions",return_code="200"} 2
grpc_server_grpc_status_code_total{grpc_method="/zitadel.management.v1.ManagementService/ListGrantedProjects",return_code="200"} 3
grpc_server_grpc_status_code_total{grpc_method="/zitadel.management.v1.ManagementService/ListProjects",return_code="200"} 3
```

Or maybe there’s a bug in the Login UI, but since everything seems to work fine, I doubt that’s the issue.

### To reproduce

1. Set up Zitadel with Docker Compose: https://zitadel.com/docs/self-hosting/deploy/compose
2. Open http://localhost:8080/debug/metrics and save the output/
3. Open http://localhost:8080/ui/console?login_hint=zitadel-admin@zitadel.localhost (no need to enter a password)
4. Open http://localhost:8080/debug/metrics again and save output
5. Find new section `HELP grpc_server_grpc_status_code_total Grpc status code counter` all results have `return_code="500"`
6. After entering the password and being redirected to the Console App, new records will appear, and some of them will have `return_code="200"`

### Screenshots

_No response_

### Expected behavior

_No response_

### Operating System

_No response_

### Relevant Configuration

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by grvijayan**
# Which Problems Are Solved

Requests without errors were mapped being mapped to GRPC status code `Unknown`, which were then being mapped as HTTP `500` status code. 

# How the Problems Are Solved

By deriving the grpc status codes from the error only when there's an error. 
When the error is `nil`, the grpc status code is set to 0 (`OK`).

# Additional Changes

N/A

# Additional Context
- Closes #10884

### CODE REVIEW

File: internal/api/grpc/server/connect_middleware/metrics_interceptor.go [hunk 1]
```diff
@@ -75,7 +75,10 @@ func RegisterGrpcTotalRequestCounter(ctx context.Context) {
 }
 
 func RegisterGrpcRequestCodeCounter(ctx context.Context, path string, err error) {
-	statusCode := connect.CodeOf(err)
+	statusCode := connect.Code(codes.OK)
```
Comment (stebenz) [inline internal/api/grpc/server/connect_middleware/metrics_interceptor.go:78]: You can also just return with `codes.OK` if error == nil.

Comment (grvijayan) [reply internal/api/grpc/server/connect_middleware/metrics_interceptor.go:78]: Don't we need to count the succeeded status codes? 
https://github.com/zitadel/zitadel/blob/f08d756013c3ac86ced7bfe3db8f955a8be53365/internal/api/grpc/server/connect_middleware/metrics_interceptor.go#L84-L88

Comment (stebenz) [reply internal/api/grpc/server/connect_middleware/metrics_interceptor.go:78]: True, I missed that, which should mean that now we handle the empty code as http status code OK.
Can you quickly check if that still behaves the same in the mapping for the ReturnCode attribute?

Comment (grvijayan) [reply internal/api/grpc/server/connect_middleware/metrics_interceptor.go:78]: Yes, it maps it to HTTP status 200:
image

**Review by stebenz — APPROVED** [review]
