### PR TITLE
fix: correctly "or"-join ldap userfilters

### LINKED ISSUE #7003: [Bug]: LDAP -  wrong searchquery using more than one user filters
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.41.1, latest

### Database

CockroachDB

### Database Version

23.1.12

### Describe the problem caused by this bug

The resulting query contains and directive instead of or.

### To reproduce

Configure ldap adding more User filters,  cannot login to using ldap (user not found)

### Screenshots

_No response_

### Expected behavior

_No response_

### Operating System

_No response_

### Relevant Configuration

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by stebenz**
# Which Problems Are Solved

LDAP userfilters are joined, but as it not handled as a list of filters but as a string they are not or-joined.

# How the Problems Are Solved

Separate userfilters as list of filters and join them correctly with "or" condition.

# Additional Changes

None

# Additional Context

Closes #7003

### CODE REVIEW

File: internal/idp/providers/ldap/session.go [hunk 1]
```diff
@@ -194,7 +194,7 @@ func trySearchAndUserBind(
 	searchQuery := queriesAndToSearchQuery(
```
Comment (IAM-marco) [inline internal/idp/providers/ldap/session.go:194]: I'm getting an unused parameter warning on `rootCA` (line 192).

If it's not an error, it can be removed all the way up to `tryBind()`

**Review by IAM-marco — CHANGES_REQUESTED** [review]
Minor unused param to remove

File: internal/idp/providers/ldap/session.go (hunk 1 above)
Comment (stebenz) [reply internal/idp/providers/ldap/session.go:192]: Good catch, I removed the param.

**Review by IAM-marco — APPROVED** [review]

**Review by IAM-marco — CHANGES_REQUESTED** [review]
There are some integration tests failing on ListOrganisations .

I think it's related to some other stuff being merged ?

Not sure what's the procedure here

**Review by IAM-marco — APPROVED** [review]
