### PR TITLE
fix(eventstore): retry push on primary key sequence violation

### LINKED ISSUE #7202: [Bug]: Duplicate Key `events2_pkey` on Token Endpoint
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

Cloud

### Database

None

### Database Version

_No response_

### Describe the problem caused by this bug

When requesting tokens on the token endpoint, we get the following errors regularly:

`ERROR: duplicate key value violates unique constraint \"events2_pkey\" (SQLSTATE 23505)`

### To reproduce

We use Zitadel in the conformance tests of [oidcc](https://github.com/erlef/oidcc).

Test: https://github.com/erlef/oidcc/blob/d57635e8a7bea3352ab2b4091fc1ec679663f884/test/oidcc_test.exs#L148

Example CI Run with failure: https://github.com/erlef/oidcc/actions/runs/7476817164/job/20348100452

### Screenshots

_No response_

### Expected behavior

Test passes every time

### Operating System

GitHub Actions on Ubuntu Latest

### Relevant Configuration

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by muhlemmer**
This change retries pushing of events if there is an unique constraint violation on the primary key of the eventstore.

Because we do a `SELECT .. FOR UPDATE` to establish the latest sequence number, many concurent pushes on the same aggregate ID might result in duplicate sequence numbers and the push will fail. We will now retry the complete push transaction, only if the error was created by the specific constraint `events2_pkey` with SQL state `23505`.

A `MaxRetries` field is added to the event store config to prevent endless retries is the context timeout is not set. `defaults.yaml` sets the value to 5. As during reproduction of the issue, the bug seems to occur a few times out of 1000 requests, 5 retries should be more than enough. If the unique constraint error still exists after 5 retries, there might be another issue worth investigating.

Closes #7202

### Definition of Ready

- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [x] PR is linked to the corresponding user story
- [x] Acceptance criteria are met
- [x] All open todos and follow ups are defined in a new ticket and justified
- [x] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [x] No debug or dead code
- [x] My code has no repetitions
- [x] Critical parts are tested automatically
- [x] Where possible E2E tests are implemented
- [x] Documentation/examples are up-to-date
- [x] All non-functional requirements are met
- [x] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Review by muhlemmer — COMMENTED** [review]
- [x] TODO: (unit) test.

File: internal/eventstore/eventstore.go [hunk 1]
```diff
@@ -77,7 +83,23 @@ func (es *Eventstore) Push(ctx context.Context, cmds ...Command) ([]Event, error
...
+	// https://github.com/zitadel/zitadel/issues/7202
+retry:
+	for i := 0; i <= es.maxRetries; i++ {
+		events, err = es.pusher.Push(ctx, cmds...)
+		var pgErr *pgconn.PgError
+		if !errors.As(err, &pgErr) || pgErr.ConstraintName != "events2_pkey" || pgErr.SQLState() != "23505" {
+			break retry
+		}
+		logging.WithError(err).Info("eventstore push retry")
+	}
```
Comment (adlerhurst) [inline internal/eventstore/eventstore.go:102]: As discussed I would first try to set the isolation level of the transaction [here](https://github.com/zitadel/zitadel/blob/a88662bb3a50e48dae06b41705fd9ee342022a1a/internal/eventstore/v3/push.go#L22) to serialisable and set the max retry to the configured one

**Review by adlerhurst — APPROVED** [review]

File: internal/eventstore/eventstore.go (hunk 1 above)
Comment (muhlemmer) [reply internal/eventstore/eventstore.go:102]: As discussed, using `LevelSerializable` instead of retry brings back the bug.
